#!/usr/bin/env python3
"""Builds data/trip.json from the research. Re-run after editing; the app reads the JSON directly."""
import json, datetime

UPDATED = datetime.datetime.now(datetime.timezone.utc).replace(microsecond=0).isoformat().replace('+00:00', 'Z')
RATE = 108  # JPY per AUD used for planning (mid-market ~110 in Sep 2026; 108 leaves room for card spreads)

def item(id, time, type, title, **kw):
    d = dict(id=id, time=time, type=type, title=title, status=kw.pop('status', 'planned'))
    d.update({k: v for k, v in kw.items() if v is not None})
    return d

days = [
  dict(id='d0208', date='2027-02-08', title='Fly out via Sydney and Melbourne', base='Overnight flight', notes='Times on this day are shown in local time at each airport. Sydney and Melbourne are one hour ahead of Queensland in February (daylight saving).', items=[
    item('a1', '06:00', 'transfer', 'Drive Gympie → Brisbane Airport', location='Bruce Hwy, ~167 km, about 1h45', notes='Book AIRPARK online beforehand (free shuttle every 10-15 min to the domestic terminal). Leaving at 6 puts you at the terminal by ~8:00. Jetstar check-in opens 2 h before and bag drop closes 40 min before departure (9:05), so 8:00-8:15 is the target.', cost=None),
    item('a2', '09:45', 'flight', 'JQ815 Brisbane → Sydney (booked, Classic Reward)', location='BNE domestic → SYD T2', endTime='12:20', status='booked', notes='Jetstar, economy Classic Reward. Departs 9:45 Queensland time, lands 12:20 Sydney time (Sydney is an hour ahead in February). Six hours of buffer before QF481. Bags are NOT checked through to Narita on Jetstar: you collect them in Sydney. Reward bookings include a 20 kg bag but the confirmation sometimes shows 0 kg; check it.'),
    item('a2b', '12:35', 'transfer', 'Collect bag, walk T2 → T3, re-check bag with Qantas for QF481', location='Sydney T2 baggage hall → covered walkway (7 min) → T3 Qantas bag drop', endTime='13:15', notes='Qantas accepts domestic bags from about 6 hours before departure, so from 12:30 you are fine. Check in for QF481 online the day before (24 h out) so you only need the bag drop. Then security and up to the lounge. If the bag drop refuses the bag early, wait landside at the T3 cafes until it opens; the lounge is airside.'),
    item('a3', '13:20', 'activity', 'Qantas Domestic Business Lounge, Sydney T3', location='Opposite gates 4-5, up the escalator, left door', notes='Your Business ticket (QF481 boarding pass) gets you in. Five hours: shower, eat lightly (the Melbourne First Lounge dinner is better), charge everything, download offline maps.'),
    item('a4', '18:30', 'flight', 'QF481 Sydney → Melbourne', location='SYD T3 → MEL T1', endTime='20:05', status='booked', notes='Business, A321neo, 1h35. Confirmed.'),
    item('a5', '20:15', 'transfer', 'Melbourne T1 → T2 walk, then immigration', location='Covered walkway, one level up, 3-5 min', notes='Bags transfer automatically on the one booking. Allow 30-40 min for security and outbound immigration.'),
    item('a6', '21:00', 'activity', 'Qantas International First Lounge, Melbourne T2 (Titanium pass)', location='Airside, level 3, escalator near gates 9-10', notes='Use one of your two Titanium First Lounge invitations here (show it in the Qantas app). Proper restaurant dining, so skip the Sydney lounge food and eat here. Be at the gate by ~10:45pm. Fallback if anything goes wrong with the pass: the International Business Lounge on level 1 is covered by the ticket.'),
    item('a7', '23:30', 'flight', 'QF49 Melbourne → Tokyo Narita', location='MEL T2 → NRT T2', endTime='07:50', status='booked', notes='Business, A330-200, 10h20, lands 7:50am Tuesday. Sleep as much as you can: Japan is only 1 hour behind Queensland, so jet lag is minimal.'),
  ]),
  dict(id='d0209', date='2027-02-09', title='Land, straight down to Osaka', base='Osaka', notes='Long travel day on purpose: it puts you in Osaka the night before the calmest weekday to do Universal Studios.', items=[
    item('b1', '07:50', 'note', 'Land Narita T2, immigration and customs', location='Narita T2', notes='Have the Visit Japan Web QR code ready (immigration + customs in one). Budget about an hour. Pick up your bag, switch on the eSIM, and withdraw ¥30,000-40,000 at the 7-Eleven ATM in the terminal (Nozawa is largely cash-only and has one foreign-card ATM, at the post office). Suica: Welcome Suica Mobile in Apple Wallet if you have an iPhone; on Android buy a physical Welcome Suica at the JR counter.'),
    item('b2', '09:45', 'train', 'Narita Express → Tokyo Station', location='NRT T2 station, B1', endTime='10:45', cost=3070, currency='JPY', notes='~55 min. Buy at the JR East ticket office or machine (the N’EX round-trip ticket for foreign passports, ¥5,200, is worth it because you come back this way on the 15th).'),
    item('b3', '11:00', 'food', 'Ekiben (station bento) from Ekibenya Matsuri', location='Tokyo Station, central passage', cost=1500, currency='JPY', notes='The most Japanese lunch there is. Grab one for the Shinkansen. Not a trendy place, just a shop with 200 regional bento.'),
    item('b4', '11:30', 'train', 'Nozomi Shinkansen Tokyo → Shin-Osaka', location='Tokyo Station, platforms 14-19', endTime='14:00', cost=14720, currency='JPY', notes='~2h30, every 10 min. Reserve a seat (opens one month ahead on smart-EX). A normal suitcase under 160 cm total is fine; only bags over 160 cm need the oversized-baggage seat.'),
    item('b5', '14:15', 'transfer', 'Shin-Osaka → hotel', location='JR local to Osaka / Fukushima, or Yumesaki line to Universal City', endTime='15:00', cost=300, currency='JPY'),
    item('b6', '15:00', 'stay', 'Check in, Osaka (2 nights)', location='See Stays for the shortlist', notes='Solo, private room. Business hotels around Fukushima or Tenma are quiet, cheap and 15-25 min from USJ by train.'),
    item('b6b', '15:20', 'transfer', 'Send the suitcase ahead by Yamato courier (takkyubin)', location='Hotel front desk', cost=3000, currency='JPY', notes='Ask the desk for “takkyubin to this address” and show the destination’s name and address in Japanese. Plan A: to the Nozawa lodging, waiting when you arrive Thursday. Plan B: to the Matsumoto hotel for Sunday 14 (write “for guest arriving 14 Feb”; hotels hold parcels). Two days is the standard lead time. Travel in between with a daypack: two or three days of clothes, USJ tickets, and in Plan A Friday’s ski base layers. Confirm beforehand that the receiving place accepts parcels (most do).'),
    item('b6c', '16:15', 'activity', 'Nintendo OSAKA store (optional, 45 min)', location='Daimaru Umeda 13F, 5 min walk from JR Osaka Station', endTime='17:00', status='idea', notes='The official Nintendo store, exclusive merchandise, quieter than the USJ shops on Wednesday. Open 10:00-20:00. Borrowed from your friend’s Tokyo list (theirs was the Shibuya Parco store).'),
    item('b7', '17:00', 'activity', 'Walk Nakazakicho and Tenma', location='Nakazakicho (old wooden lanes) → Tenjinbashisuji shopping arcade → Tenma', notes='Low-key neighbourhoods a short train ride from Umeda. Tenjinbashisuji is 2.6 km of covered arcade where locals shop.'),
    item('b8', '18:30', 'food', 'Dinner in the Tenma izakaya alleys', location='Around Tenma station, under the tracks', cost=3500, currency='JPY', notes='Standing bars and tiny izakaya, mostly Japanese customers. Order doteyaki (beef tendon simmered in miso) and kushikatsu. Early night; tomorrow starts at 7.'),
  ]),
  dict(id='d0210', date='2027-02-10', title='Universal Studios Japan and Super Nintendo World', base='Osaka', notes='Wednesday is the calmest weekday in the window (Thursday is a public holiday, and the weekend follows). Buy the Studio Pass and an Express Pass that includes Super Nintendo World entry as soon as they go on sale for this date.', items=[
    item('c1', '07:00', 'train', 'Train to Universal City', location='Osaka Station platform 1 → Universal City (JR Yumesaki line, ~12 min direct)', cost=200, currency='JPY'),
    item('c2', '07:45', 'note', 'Be at the gates before official opening', location='USJ main entrance', notes='Posted opening is usually 9:00-9:30 in February but the park regularly opens 30-60 min early. Being there by 7:45 matters if you are relying on the free timed-entry ticket. Log into the USJ app the night before and make sure the eSIM has data: the timed-entry ticket is app-only (since Jan 2026) and needs signal at the gate.'),
    item('c3', '08:30', 'activity', 'Enter USJ; claim Super Nintendo World timed entry in the app the second you are through the gate', location='USJ', cost=10900, currency='JPY', notes='1-Day Studio Pass, date-priced (¥8,900 low season up to ¥11,800 peak in 2026; Feb 2027 not published yet). If you bought an Express Pass with area entry you already have a slot and can skip the scramble.'),
    item('c4', '09:30', 'activity', 'Super Nintendo World: Mario Kart, Yoshi’s Adventure, Donkey Kong Country', location='Super Nintendo World', cost=4800, currency='JPY', notes='The ¥4,800 is the Power-Up Band (optional but it is the whole point of the key challenges and Bowser Jr boss fight). Ride Mario Kart first, then Donkey Kong’s Mine Cart, then wander.'),
    item('c5', '12:30', 'food', 'Kinopio’s Cafe (Toad’s cafe)', location='Super Nintendo World', cost=2500, currency='JPY', notes='Reserve in the app on the day if slots show. Otherwise Yoshi’s Snack Island for a quick bite.'),
    item('c6', '14:00', 'activity', 'Rest of the park: Jurassic Park, Harry Potter area, Jaws', location='USJ', endTime='19:00', notes='Single Rider lines are the solo traveller’s cheat code and are free. February weekdays historically close around 7pm, so the day is shorter than summer: front-load Nintendo World.'),
    item('c7', '19:45', 'food', 'Okonomiyaki dinner back in town', location='A neighbourhood okonomiyaki counter near the hotel (see Food)', cost=1800, currency='JPY'),
  ]),
  dict(id='d0211', date='2027-02-11', title='Osaka → Narai-juku (Edo post town) → Nozawa Onsen', base='Nozawa Onsen', notes='National Foundation Day, so reserve every seat a month ahead. The Shinano express runs straight through the Kiso valley, so this is the day to see rural Japan for free: hop off at Kiso-Fukushima, ride one local stop to Narai-juku, walk the 1 km Edo-period street in the snow, then carry on to Nagano. Travel hands-free: the suitcase goes ahead by courier from Osaka (see Tuesday).', items=[
    item('e1', '08:00', 'transfer', 'Check out (daypack only), to Shin-Osaka', location='Shin-Osaka', cost=300, currency='JPY'),
    item('e2', '08:40', 'train', 'Nozomi Shin-Osaka → Nagoya', location='Shin-Osaka', endTime='09:30', cost=6880, currency='JPY', notes='~50 min, reserved seat.'),
    item('e3', '10:00', 'train', 'Limited Express Shinano Nagoya → Kiso-Fukushima', location='Nagoya, Chuo line platforms', endTime='11:25', cost=6000, currency='JPY', notes='Reserved seat on the holiday. Sit on the left for the Kiso river. Buy the ticket through to Nagano with a break at Kiso-Fukushima, or two tickets; either is fine.'),
    item('e4', '11:45', 'train', 'Local train Kiso-Fukushima → Narai', location='Kiso-Fukushima, Chuo line local (about every hour)', endTime='12:05', cost=330, currency='JPY', notes='20 minutes. Check the local timetable when you reserve the Shinano so the connection is short.'),
    item('e5', '12:10', 'activity', 'Narai-juku: the best-preserved post town on the old Nakasendo road', location='Narai station → 1 km of Edo-period wooden inns and shops', endTime='14:30', cost=0, currency='JPY', notes='A working village, not a theme park: lacquerware workshops, a sake shop, temples up the side lanes, snow on the eaves. Narai station has no lockers but a ¥300 bag-minding desk (8:30-16:00) if you are carrying anything. Lunch here: soba or gohei-mochi (grilled rice cake with walnut-miso), the Kiso valley specialty. The Kiso Ohashi bridge and Kamidonya museum are worth 20 minutes.'),
    item('e6', '13:00', 'food', 'Gohei-mochi and Kiso soba in Narai', location='Any shop on the main street with a menu outside', cost=1500, currency='JPY'),
    item('e7', '14:40', 'train', 'Local train Narai → Shiojiri, then Shinano Shiojiri → Nagano', location='Narai station', endTime='16:35', cost=4500, currency='JPY', notes='Local 25 min to Shiojiri, change to the Shinano (about hourly) for ~65 min to Nagano. Reserve the Shiojiri → Nagano seat too.'),
    item('e8', '17:00', 'train', 'Hokuriku Shinkansen Nagano → Iiyama', location='Nagano Station', endTime='17:12', cost=1500, currency='JPY', notes='12 minutes. The Nozawa Onsen Liner leaves about 10 min after each Shinkansen.'),
    item('e9', '17:25', 'bus', 'Nozawa Onsen Liner → Nozawa Onsen', location='Iiyama Station, bus stop out the front', endTime='17:50', cost=600, currency='JPY', notes='25 min. Taxi is the fallback (¥6,000-7,000). Tell the lodging you arrive about 6pm so dinner is held.'),
    item('e10', '18:00', 'stay', 'Check in, Nozawa Onsen (5 nights)', location='See Stays for the shortlist and how to book', notes='Your suitcase should be waiting (sent by courier on Tuesday). If it is not, the daypack has tomorrow’s ski layers.'),
    item('e11', '18:30', 'food', 'Ryokan dinner (or Wakagiri if no meals booked)', location='Lodging / main street', cost=3000, currency='JPY', notes='Ryokan dinners are served at a fixed time; say so at check-in. If you are eating out, Wakagiri is the local favourite for a home-style set meal.'),
    item('e12', '20:00', 'activity', 'Oyu, the main public bathhouse', location='Centre of the village', cost=0, currency='JPY', notes='13 free soto-yu bathhouses run by the village. Wash first, no towel in the water, keep it quiet, no photos. Bring a small towel; expect it hot.'),
  ]),
  dict(id='d0212', date='2027-02-12', title='Ski Nozawa, day 1', base='Nozawa Onsen', notes='Thursday was a stand-alone public holiday, so Friday is the comparatively quiet day before the weekend crowd arrives. Be on the Nagasaka gondola at opening (8:30) and head to Yamabiko at the top.', items=[
    item('f0', '07:45', 'activity', 'Ski rental fitting (pre-booked, 4 days)', location='Village rental shop', cost=17800, currency='JPY', notes='4 days x ¥4,450 standard set (skis, boots, poles) at a village shop; the resort shop is ¥5,500/day. Book online in January with your boot size in cm: big sizes (29 cm+) run out in peak weeks. Ski wear can be rented too.'),
    item('f1', '08:15', 'ski', 'Nozawa Onsen Snow Resort, full day', location='Nagasaka gondola', endTime='16:00', cost=8000, currency='JPY', notes='Special Pack: 1-day lift pass + ¥1,000 lunch voucher (2025-26 price; expect +5-10%). 297 ha, 1,085 m vertical, 10 km longest run (Skyline). Yamabiko for tree runs, Uenotaira for cruising.'),
    item('f2', '12:30', 'food', 'Lunch on the mountain with the voucher', location='Yamabiko or Uenotaira restaurants', cost=500, currency='JPY', notes='Curry rice or ramen; the voucher covers most of it.'),
    item('f3', '16:30', 'activity', 'Onsen: try a different soto-yu (Kuma no Tearai or Shinyu)', location='Village', cost=0, currency='JPY'),
    item('f4', '18:30', 'food', 'Soba at Sobadokoro Daimon', location='Main street, 100-year-old family shop', cost=1800, currency='JPY', notes='Hand-cut Shinshu soba. Order it zaru (cold) even in winter; it is how locals judge a soba shop.'),
  ]),
  dict(id='d0213', date='2027-02-13', title='Ski Nozawa, day 2', base='Nozawa Onsen', notes='Saturday of the long weekend: busy, so early start. Karasawa and Paradise are quieter than the gondola-top runs. Night skiing on Hikage runs on selected nights; check the board. Rental gear is easiest to fit first thing Friday, so plan on being at the shop when it opens.', items=[
    item('g1', '08:15', 'ski', 'Nozawa Onsen Snow Resort, full day', location='Hikage gondola', endTime='16:00', cost=8000, currency='JPY', notes='Special Pack again. Explore Karasawa and Paradise; the Skyline run top to bottom late afternoon when it empties.'),
    item('g2', '12:30', 'food', 'Mountain lunch', location='On mountain', cost=500, currency='JPY'),
    item('g3', '17:00', 'activity', 'Onsen eggs at the Ogama', location='Ogama (the village’s boiling cooking spring, locals only in the water but you can watch and buy eggs nearby)', cost=300, currency='JPY'),
    item('g4', '18:30', 'food', 'Izakaya dinner: basashi (horse sashimi) and nozawana', location='A village izakaya (see Food)', cost=3500, currency='JPY'),
  ]),
  dict(id='d0214', date='2027-02-14', title='Rural day: Togakushi shrine in the snow, then Zenko-ji', base='Nozawa Onsen', notes='Sunday is the most crowded ski day of the trip (long-weekend Tokyo crowd), so it is the cheapest day to give up. Togakushi is a mountain shrine village above Nagano: a 2 km avenue of 400-year-old cedars leading to the inner shrine, all under deep snow in February, plus the soba the village is famous for. Back via Zenko-ji, one of Japan’s great temples. If it is dumping powder on Sunday morning, swap this for skiing and call the day a rest instead; the ski item below is kept as the alternative.', items=[
    item('h1', '08:05', 'bus', 'Nozawa Onsen Liner → Iiyama, Shinkansen → Nagano', location='Village bus stop → Iiyama → Nagano', endTime='09:05', cost=2100, currency='JPY', notes='Check the Liner and Shinkansen times the night before; Sunday services are the same as weekdays.'),
    item('h2', '09:30', 'bus', 'Alpico bus 70 Nagano Station → Togakushi', location='Nagano Station east side, bus stop 7', endTime='10:35', cost=1450, currency='JPY', notes='About 60 min to Chusha (middle shrine). In winter a separate winter service stops at the Okusha entrance; if the bus you are on does not, get off at Chusha and walk up the road ~30 min or take a taxi. The Zenko-ji & Togakushi 1-day bus ticket (Alpico) covers the whole day’s buses and is cheaper than singles.'),
    item('h3', '10:40', 'activity', 'Okusha cedar avenue and inner shrine', location='Okusha entrance → Zuishinmon gate → Okusha', endTime='13:00', cost=0, currency='JPY', notes='20 min flat walk through the cedars to the red Zuishinmon gate, then a steeper 20-30 min to the inner shrine, all on packed snow. Bring or buy simple crampons (Workman or Don Quijote sell them for ~¥1,500) and waterproof boots; ski gloves and shell are perfect. Quiet, no ropes, no gates: this is the rural Japan you asked for.'),
    item('h4', '13:15', 'food', 'Togakushi soba at Chusha', location='Around Chusha (middle shrine): Uzuraya is the famous one, several quieter shops nearby', cost=1600, currency='JPY', notes='Togakushi soba is served in small “bocchi” bundles on a bamboo tray. Order zaru, add the local wasabi. Cash.'),
    item('h5', '14:10', 'activity', 'Chusha shrine and the ninja museum village (optional)', location='Chusha', endTime='15:00', cost=0, currency='JPY', notes='Chusha has an 800-year-old triple cedar at its gate. Skip the ninja stuff unless it amuses you.'),
    item('h6', '15:10', 'bus', 'Bus 70 Togakushi → Zenko-ji (Daimon stop)', location='Chusha bus stop', endTime='16:05', cost=1300, currency='JPY', notes='Get off at Zenkoji Daimon, not the station. Last buses back down are around 17:00-18:00; check the winter timetable.'),
    item('h7', '16:10', 'activity', 'Zenko-ji temple at dusk', location='Zenko-ji, Nagano', endTime='17:00', cost=600, currency='JPY', notes='1,400-year-old temple, the reason Nagano exists. Walk the main hall, do the pitch-black “kaidan meguri” tunnel under the altar to touch the key to paradise (¥600). The approach street (Nakamise) has oyaki and miso shops.'),
    item('h8', '17:15', 'train', 'Nagano → Iiyama → Nozawa Onsen', location='Nagano Station (15 min walk or bus from Zenko-ji)', endTime='18:40', cost=2100, currency='JPY'),
    item('h9', '19:00', 'food', 'Last Nozawa dinner: oyaki, nozawana and a nabe hotpot', location='Village', cost=3000, currency='JPY'),
    item('h10', '20:30', 'note', 'Pack; return rental gear tonight if the shop allows, or first thing tomorrow', location='Lodging'),
    item('h11', '08:15', 'ski', 'ALTERNATIVE if it is a powder day: ski Nozawa instead', location='Nagasaka gondola', endTime='16:00', cost=8000, currency='JPY', status='skip', notes='Marked as skipped so it stays out of the budget. Flip the status to Planned and set the Togakushi items to Skipped if you choose to ski. Sunday lift lines ease after 2pm.'),
  ]),
  dict(id='d0215', date='2027-02-15', title='Ski Nozawa, day 3 (the quiet Monday)', base='Nozawa Onsen', notes='The long-weekend crowd went home last night. This is the emptiest the mountain will be all trip, which is exactly why the trip now ends Tuesday.', items=[
    item('i1', '08:15', 'ski', 'Nozawa Onsen Snow Resort, full day', location='Nagasaka gondola', endTime='16:00', cost=8000, currency='JPY', notes='Special Pack again. Skyline top to bottom with nobody on it; Yamabiko trees if it snowed overnight.'),
    item('i2', '12:30', 'food', 'Mountain lunch', location='On mountain', cost=500, currency='JPY'),
    item('i3', '16:30', 'activity', 'Onsen, then pack most of the bag', location='Village', cost=0, currency='JPY'),
    item('i4', '18:30', 'food', 'Last Nozawa dinner: basashi, nozawana, a nabe hotpot', location='Village izakaya', cost=3500, currency='JPY'),
    item('i5', '20:30', 'note', 'Confirm tomorrow: Liner time, Shinkansen reservation, rental return, cash to settle the bill', location='Lodging'),
  ]),
  dict(id='d0216', date='2027-02-16', title='Morning ski, then home via Tokyo', base='Overnight flight', notes='QF80 is booked for 19:20, so the noon bus out of Nozawa is the latest sensible one.', items=[
    item('j1', '08:30', 'ski', 'Short morning ski (optional)', location='Nagasaka gondola', endTime='10:45', cost=6000, currency='JPY', status='idea', notes='Only if the lodging allows a late checkout and the rental shop opens early. Otherwise a slow breakfast and one last bathhouse.'),
    item('j2', '11:15', 'note', 'Return rental gear, check out, settle in cash', location='Village'),
    item('j3', '12:00', 'bus', 'Nozawa Onsen Liner → Iiyama Station', location='Village bus stop', endTime='12:25', cost=600, currency='JPY'),
    item('j4', '12:45', 'train', 'Hokuriku Shinkansen Iiyama → Tokyo', location='Iiyama Station', endTime='14:40', cost=8500, currency='JPY', notes='~1h50, reserve the seat (Hakutaka services stop at Iiyama roughly hourly).'),
    item('j5', '15:00', 'train', 'Narita Express Tokyo → Narita T2', location='Tokyo Station', endTime='16:00', cost=0, currency='JPY', notes='Covered by the N’EX round trip ticket bought on day 1 (valid 14 days).'),
    item('j6', '16:15', 'note', 'Narita T2: check in, drop bag, tax-free refund counter if you shopped', location='NRT T2', notes='QF80 check-in closes 18:20. Check in online 24 h before and pick a seat.'),
    item('j7', '17:00', 'food', 'Dinner at Narita T2 food court', location='NRT T2, 4F', cost=1500, currency='JPY', notes='Tonkatsu or ramen; last Japanese meal.'),
    item('j8', '19:20', 'flight', 'QF80 Narita → Melbourne', location='NRT T2 → MEL T2', endTime='07:45', status='booked', notes='Confirmed. Overnight A330, 10h25, Economy Sale fare. Try adding Economy Plus in Manage Booking. Lands Melbourne 07:45 Wed.'),
  ]),
  dict(id='d0217', date='2027-02-17', title='Land Brisbane, drive home', base='Home', notes='', items=[
    item('k1', '07:45', 'transfer', 'Land Melbourne T2: straight to SmartGate, collect bag, customs, Qantas domestic transfer desk, walk to T1', location='MEL T2 → T1', endTime='08:50', notes='1h35 connection, protected because both flights are on the one booking; if QF80 is late Qantas rebooks you on a later Melbourne → Brisbane flight. No duty-free browsing: immigration, bag belt, customs, transfer desk, T1, gate. No time for a lounge.'),
    item('k1b', '09:20', 'flight', 'QF1256 Melbourne → Brisbane', location='MEL T1 → BNE Terminal D', endTime='10:35', status='booked', notes='QantasLink A220, 2h15. Confirmed.'),
    item('k2', '11:00', 'transfer', 'AIRPARK shuttle to the car, lunch, drive to Gympie', location='BNE → Gympie, ~1h45', notes='Two flights and a red-eye behind you: eat and have a proper coffee before the Bruce Highway. Home about 1:30pm.'),
  ]),
]

flights = dict(
  confirmed=[
    dict(id='jq815', flight='JQ815', from_='Brisbane domestic', to='Sydney T2', date='2027-02-08', arrDate='2027-02-08', dep='09:45', arr='12:20', cabin='Economy', aircraft='A320/A321', duration='1h35', notes='Jetstar, Economy Classic Reward, 5,700 pts + A$43 taxes. Brisbane Terminal D (domestic). Separate booking from the Business reward, so not protected, but 6 hours of buffer. Bags not through-checked: collect at T2, re-check at T3.', cashAud=43),
    dict(id='qf481', flight='QF481', from_='Sydney T3', to='Melbourne T1', date='2027-02-08', arrDate='2027-02-08', dep='18:30', arr='20:05', cabin='Business', aircraft='A321neo', duration='1h35', notes='Business Classic Reward. Domestic leg; check-in at Sydney T3. Same booking as QF49, so the connection is protected.'),
    dict(id='qf80', flight='QF80', from_='Tokyo Narita T2', to='Melbourne T2', date='2027-02-16', arrDate='2027-02-17', dep='19:20', arr='07:45', cabin='Economy (Sale fare)', aircraft='A330', duration='10h25', notes='Paid fare, ¥92,570 (about A$857) for both sectors. Economy Sale fares are NOT eligible for Classic Upgrade Rewards, so a points upgrade to Business is off the table on this ticket. Economy Plus (extra legroom) is a seat product and may still be purchasable in Manage Booking with cash or points: worth trying. 30 kg checked allowance.', cashAud=857),
    dict(id='qf1256', flight='QF1256', from_='Melbourne T1', to='Brisbane (Terminal D)', date='2027-02-17', arrDate='2027-02-17', dep='09:20', arr='10:35', cabin='Economy', aircraft='A220-300 (QantasLink)', duration='2h15', notes='Same booking as QF80, so the 1h35 Melbourne connection is protected: if QF80 is late, Qantas moves you to a later Melbourne → Brisbane flight (roughly hourly) at no cost. Still, go straight to SmartGate on landing: 1h35 is enough, not generous.'),
    dict(id='qf49', flight='QF49', from_='Melbourne T2', to='Tokyo Narita T2', date='2027-02-08', arrDate='2027-02-09', dep='23:30', arr='07:50', cabin='Business', aircraft='A330-200', duration='10h20', notes='Business Classic Reward. Seasonal Monday service (runs Sun/Mon/Wed/Fri, 2 Dec 2026 to late Mar 2027). Taxes paid: A$450.', cashAud=450),
  ],
  legs=[
    dict(id='leg-feeder', name='Home to Sydney, Mon 8 Feb', chosenOptionId='opt-jq815', notes='BOOKED: Jetstar JQ815 as a Classic Reward, landing 12:20 with six hours to spare. Being Jetstar it lands at T2 and the bag has to be collected and re-checked at T3, which the 6-hour buffer absorbs easily. Other options are kept below for the record.', options=[
      dict(id='opt-jq815', rank=0, label='Jetstar JQ815 Brisbane → Sydney (BOOKED)', route='BNE → SYD T2', date='2027-02-08', dep='09:45', arr='12:20', duration='1h35', cashAud=0, priceNote='booked on points', points=5700, pointsTaxAud=27, status='booked', notes='Economy Classic Reward. 20 kg bag should be included; confirm on the booking. Lands T2; walk 7 min to T3 and re-check the bag with Qantas.'),
      dict(id='opt-qf-bne', rank=1, label='Qantas Brisbane → Sydney, late morning', route='BNE → SYD T3', date='2027-02-08', dep='11:30', arr='14:05', duration='1h35', cashAud=140, priceNote='A$95-365 range; est. mid', points=9200, pointsTaxAud=58, status='skip', notes='Recommended. Park at BNE AIRPARK (A$109 for 8 days). With QF62 landing at BNE on the way home, this is the cheapest and simplest overall. 11:30 Queensland time → ~2:05pm Sydney time (AEDT): 4+ hours of buffer and lounge. Any QF flight landing before 3pm Sydney time works.'),
      dict(id='opt-qf-mcy', rank=2, label='Qantas QF903 Sunshine Coast → Sydney', route='MCY → SYD T3', date='2027-02-08', dep='12:15', arr='15:05', duration='1h40', cashAud=160, priceNote='from ~A$130', points=9200, pointsTaxAud=58, status='skip', notes='1 h from Gympie, parking ~A$90 for 8 days, no tolls. But if QF903 is cancelled the next Qantas flight lands after QF481 has gone, and the homeward flight lands at Brisbane, so you would need a A$55-85 shuttle back to the car. Times shown in Sydney time (AEDT).'),
      dict(id='opt-jq-mcy', rank=3, label='Jetstar JQ787 Sunshine Coast → Sydney', route='MCY → SYD T2', date='2027-02-08', dep='11:30', arr='14:15', duration='1h45', cashAud=90, priceNote='from ~A$67 + bag', status='skip', notes='Cheapest fare, but arrives T2: collect bags, walk 7 min to T3, re-check, re-screen. No through-checking to Narita.'),
      dict(id='opt-qf905', rank=4, label='Qantas QF905 Sunshine Coast → Sydney, 7am (safest from MCY)', route='MCY → SYD T3', date='2027-02-08', dep='07:00', arr='09:50', duration='1h40', cashAud=150, points=9200, pointsTaxAud=58, status='skip', notes='Lowest risk if you insist on MCY: a whole day of fallback options. Long day in Sydney though (8+ hours in the lounge).'),
    ]),
    dict(id='leg-home', name='Japan to home, Tue 16 Feb', chosenOptionId='opt-qf80', notes='BOOKED: QF80 + QF1256 as a paid Economy Sale fare. Background kept below. Big finding: the Brisbane flight (QF62) has no Premium Economy cabin at all, so “book economy and upgrade to PE” does not exist on it. The only Qantas Tokyo flight with PE is the 6:55am Haneda → Sydney. Realistic comfort upgrades: Economy Plus extra-legroom seats on the A330 (new from Sep 2026), or a Business Classic Reward if a seat appears. Points numbers marked “est.” are inferred from the Aug 2025 price rise; confirm on qantas.com when booking.', options=[
      dict(id='opt-qf62-econ', rank=1, label='QF62 Narita → Brisbane, Economy Classic Reward', route='NRT → BNE', date='2027-02-16', dep='21:45', arr='07:45', duration='~9h', cashAud=720, priceNote='cash from ~A$720', points=29000, pointsTaxAud=150, status='skip', notes='No reward seats on 16 Feb when checked (Sep 2026). Keep an AwardFares alert running in case a batch is released; changing a booked reward costs a fee, so only switch for a Business seat. ~29,000 pts (est.) + ~A$120-170 taxes (Japan’s departure tax tripled to ¥3,000 from July 2026, so ex-Japan taxes are a little higher than older guides say). Add Economy Plus (extra legroom, ~19,500 pts or ~A$100-150 cash on similar routes) for comfort. Lands straight into Brisbane where the car is.'),
      dict(id='opt-qf62-bus', rank=3, label='QF62 Narita → Brisbane, Business Classic Reward', route='NRT → BNE', date='2027-02-16', dep='21:45', arr='07:45', duration='~9h', cashAud=3500, priceNote='cash ~A$3,000+', points=82100, pointsTaxAud=320, status='idea', notes='82,100 pts (confirmed post-Aug-2025 price) + ~A$250-350 taxes. You have the points. Availability at Bronze in peak February is the only question; set alerts.'),
      dict(id='opt-jq10', rank=4, label='Jetstar JQ10 Narita → Brisbane, economy', route='NRT → BNE', date='2027-02-16', dep='20:50', arr='06:45', duration='8h55', cashAud=409, priceNote='from ~A$409 + bag/meal', points=24000, pointsTaxAud=110, status='idea', notes='Cheapest points option (Jetstar table, ~24,000 pts est.; includes 20 kg bag). 787, no PE; you can bid for Jetstar Business with points + cash.'),
      dict(id='opt-jq24', rank=5, label='Jetstar JQ24 Osaka KIX → Brisbane (only if the trip is flipped to end in Osaka)', route='KIX → BNE', date='2027-02-16', dep='21:45', arr='07:25', duration='8h45', cashAud=420, priceNote='from ~A$400', points=24000, pointsTaxAud=110, status='idea', notes='Runs ~4x weekly; confirm Monday operates. Would let you do USJ on the last day and skip the Tokyo backtrack, at the cost of USJ on a Monday instead of Wednesday.'),
      dict(id='opt-qf80', rank=0, label='QF80 Narita → Melbourne 19:20 + QF1256 Melbourne → Brisbane 09:20 (BOOKED, cash Economy Sale)', route='NRT → MEL → BNE', date='2027-02-16', dep='19:20', arr='10:35', duration='10h25 + 1h35 change + 2h15', cashAud=857, priceNote='¥92,570 paid', status='booked', notes='Booked as a paid Economy Sale fare (QF62 had no reward seats). Consequences: no points upgrade is possible on a Sale fare, so the 164k points stay in the bank for another trip; Economy Plus extra legroom may still be added in Manage Booking. 1h35 in Melbourne is protected because both flights are on one booking. Lands Brisbane 10:35 Wed, home early afternoon.'),
      dict(id='opt-qf26', rank=6, label='QF26 Haneda → Sydney, the only flight with Premium Economy', route='HND → SYD', date='2027-02-17', dep='06:55', arr='18:55', duration='~10h', cashAud=900, priceNote='economy cash est.', points=36200, pointsTaxAud=140, status='idea', notes='3-class A330 from Oct 2026. Economy ~36,200 pts est., PE ~74,000 pts est. Departs 6:55am (check-in from 4am, before trains run), so you would sleep at a Haneda hotel on the 15th and then still need SYD → Brisbane/Sunshine Coast. Only worth it if PE is the priority over everything else.'),
    ]),
  ],
  lounges=[
    dict(airport='Sydney T3 (Mon 8 Feb, ~2pm-6pm)', lounge='Qantas Domestic Business Lounge', access='yes', notes='Access comes from the Business cabin on your Classic Reward, not from status or passes. Entry opposite gates 4-5, up the escalator; Business Lounge is the left-hand door. Open until the last Qantas departure. Sydney’s First Lounge is in the international terminal (T1) and is not reachable from T3.'),
    dict(airport='Melbourne T2 (Mon 8 Feb, ~9pm-10:45pm)', lounge='Qantas International Business Lounge', access='yes', notes='Airside, level 1. Covered by the Business ticket. Melbourne Airport lists a 10:15pm Monday close, but Qantas says lounges stay open until the last departure and Monday QF49 is a new service from Dec 2026: re-check the hours in January and be at the gate by 10:45pm regardless.'),
    dict(airport='Melbourne T2, First Lounge (level 3), Mon 8 Feb ~9pm-10:45pm', lounge='Qantas International First Lounge', access='yes', notes='Confirmed: your two passes are Qantas Money Titanium First Lounge invitations, which are valid at the Sydney, Melbourne and Los Angeles First Lounges when you are flying on a QF or JQ flight number. Use ONE here: escalator near gates 9-10 up to level 3, show the invitation in the Qantas app. Sit-down dining (the Neil Perry menu), spa if you book on arrival, showers. The second pass cannot be used on this trip (Narita has no Qantas First Lounge and you leave Sydney from the domestic terminal), so keep it for a later international departure. Third-party listings put closing at 10:15-11:15pm; be at the gate by 10:45pm. Invitations are cardholder-only and expire, so check the expiry date in the app now.'),
    dict(airport='Brisbane domestic (Mon 8 Feb, ~8:15-9:15am)', lounge='Qantas Club (via a Titanium card Qantas Club invitation)', access='maybe', notes='The Titanium card also gives two Qantas Club / International Business Lounge invitations a year, separate from the First Lounge ones. Qantas Club access is normally allowed when flying a Jetstar (JQ) domestic flight, so one of those invitations should open the Brisbane Qantas Club for an hour before JQ815. Check the invitation type in the app; it is a nice-to-have, not a plan.'),
    dict(airport='Sunshine Coast (MCY)', lounge='No lounges at all', access='no', notes='Small terminal, four eateries, free wifi.'),
    dict(airport='Narita T2 (Tue 16 Feb)', lounge='Economy: none. Business reward: JAL Sakura Lounge', access='no', notes='If you end up on the Business reward home, Qantas uses the JAL Sakura Lounge at Narita. In economy there is no lounge access; the 4F food court is good.'),
    dict(airport='Melbourne T1 domestic (Wed 17 Feb)', lounge='No time for one', access='no', notes='1h35 between landing and QF1256 is used up by immigration, bags, customs and the transfer. Skip the lounge.'),
  ],
)

points = dict(balance=170000, availableFrom='2026-10-15', notes='Update 13 Sep 2026: the flight home was booked as a paid Economy Sale fare, which cannot be upgraded with points (Sale classes E/N/O/Q are excluded from Classic Upgrade Rewards). Only the Jetstar feeder (5,700) has used points, so about 164k stay in the bank; Economy Plus on QF80 (~19,500 pts if offered) is the one remaining use on this trip. Prices confirmed post-5 Aug 2025: NRT→BNE Business 82,100; HND/NRT→SYD/MEL Business 98,400; short domestic (Zone 1) economy 9,200 + ~A$58. Economy Tokyo→Brisbane is estimated at ~29,000 (Zone 5) and Tokyo→Sydney/Melbourne ~36,200 (Zone 6); the exact cells were not visible from here, confirm on qantas.com. Bronze members are last in the upgrade queue and are typically only considered inside 24 h of departure, so treat any upgrade as a bonus, not a plan. Qantas’ Flight Reward Finder can be searched without logging in; AwardFares has a free Qantas search with alerts.')

stays = [
  # Osaka, 9-11 Feb (2 nights)
  dict(id='s-os1', name='Dormy Inn Premium Osaka Kitahama', town='Osaka', type='Business hotel with rooftop onsen bath', status='shortlist', pricePerNightAud=140, nights=2, priceNote='est. Feb; verify', checkIn='2027-02-09', checkOut='2027-02-11', distance='Kitahama: 20 min to Universal City by train; quiet business district by the river', url='https://www.booking.com/', notes='Dormy Inns are the solo traveller’s friend: free late-night ramen, big bath, small clean rooms. Kitahama is calm and central.'),
  dict(id='s-os2', name='Toyoko Inn Osaka Umeda Nakatsu No.1', town='Osaka', type='Budget business hotel', status='shortlist', pricePerNightAud=100, nights=2, priceNote='est. Feb; verify', checkIn='2027-02-09', checkOut='2027-02-11', distance='Nakatsu: 10 min walk to Nakazakicho, 20 min to USJ', url='https://www.toyoko-inn.com/eng/', notes='Cheapest reliable option. Free breakfast (onigiri, miso soup). Book direct; the chain often has Feb availability when others are full.'),
  dict(id='s-os3', name='Hotel Universal Port Vita', town='Osaka', type='Official partner hotel, 10 min walk to USJ', status='idea', pricePerNightAud=200, nights=2, priceNote='est. Feb; verify', checkIn='2027-02-09', checkOut='2027-02-11', distance='Universal City: walk to the park gates, early-entry perks on some plans', url='https://www.hoteluniversalportvita.com/', notes='Pay for convenience on USJ day only if the price is close. The Universal City area is a theme-park precinct, not a neighbourhood.'),
  # Nozawa Onsen, 11-16 Feb (5 nights). Solo: most places sell twin rooms with a single supplement.
  dict(id='s-nz1', name='Nozawa Peaks (guesthouse, book direct)', town='Nozawa Onsen', type='Japanese-style guesthouse, private rooms, shared bath', status='shortlist', pricePerNightAud=150, nights=5, priceNote='est. Feb; verify', checkIn='2027-02-11', checkOut='2027-02-16', distance='4 min walk to the lifts', url='https://nozawapeaks.com/', notes='Books direct for 2026-27 on its own site, English, used to solo guests. Ask for a single room rate.'),
  dict(id='s-nz2', name='Lodge Nagano (Aussie-run lodge)', town='Nozawa Onsen', type='Lodge, private room, shared bath', status='shortlist', pricePerNightAud=140, nights=5, priceNote='est. Feb; verify', checkIn='2027-02-11', checkOut='2027-02-16', distance='~100 m from the slopes, short walk to the village centre', url='https://www.lodgenagano.com/', notes='Affordable, easy English, solo-friendly. Also listed by Nozawa Holidays. You will be surrounded by Australians, which is the trade-off.'),
  dict(id='s-nz3', name='Haus St. Anton (family-run pension hotel)', town='Nozawa Onsen', type='15-room boutique pension, private rooms with bath', status='shortlist', pricePerNightAud=280, nights=5, priceNote='Classic room from ~US$184; verify solo rate', checkIn='2027-02-11', checkOut='2027-02-16', distance='Village, near the Nagasaka side', url='https://st-anton.jp/en/stay/', notes='Japanese family-run, European style, non-smoking, famous jam factory downstairs. Book direct on their English page. Top of the budget but the most Banff-like small hotel in the village.'),
  dict(id='s-nz4', name='Nozawa Onsen Hotel', town='Nozawa Onsen', type='Hotel, single rooms exist', status='shortlist', pricePerNightAud=300, nights=5, priceNote='US$177-241 typical; verify', checkIn='2027-02-11', checkOut='2027-02-16', distance='Village centre', url='https://www.kayak.com/Nozawa-Onsen-Hotels-Nozawa-Onsen-Hotel.2312608.ksp', notes='One of the few places with proper single rooms and its own onsen. Check Rakuten Travel and Jalan for single-occupancy plans; often cheaper than Booking.com.'),
  dict(id='s-nz5', name='Lodge Matsuya / Lodge Nakajima (local family lodges)', town='Nozawa Onsen', type='Minshuku-style lodge, private room, shared bath', status='shortlist', pricePerNightAud=110, nights=5, priceNote='est.; verify', checkIn='2027-02-11', checkOut='2027-02-16', distance='Village', url='https://www.tripadvisor.com/Hotel_Review-g1120620-d1137257-Reviews-Lodge_Matsuya-Nozawaonsen_mura_Shimotakai_gun_Nagano_Prefecture_Koshinetsu_Chubu.html', notes='Japanese-run, simple, warm, cheap. These are the ones that rarely show on Booking.com: use Rakuten/Jalan or email in simple English.'),
  dict(id='s-nz6', name='Seisenso Inn (minshuku)', town='Nozawa Onsen', type='Family-run minshuku, private room, shared bath', status='shortlist', pricePerNightAud=90, nights=5, priceNote='from ~¥5,000 pp; single surcharge likely', checkIn='2027-02-11', checkOut='2027-02-16', distance='In the village, 5-10 min walk to Nagasaka gondola', url='https://nozawa-onsen.com/nozawa-accommodation/nozawa-onsen-ryokan-accommodation/', notes='Closest to the Banff-motel price point. Ask for a single tatami room with breakfast.'),
  dict(id='s-nz7', name='Ginrei Lodge or Nozawa Springs Lodge (via Nozawa Holidays)', town='Nozawa Onsen', type='Lodge, private room', status='idea', pricePerNightAud=150, nights=5, priceNote='est.; verify', checkIn='2027-02-11', checkOut='2027-02-16', distance='Village', url='https://www.nozawaholidays.com/properties/', notes='Nozawa Holidays manages a dozen lodges and will tell you in one email which ones still have a solo room for 11-16 Feb. Easiest single point of contact.'),
  dict(id='s-nz8', name='Nozawa Dream Central (budget)', town='Nozawa Onsen', type='2-star, cheapest in the village', status='idea', pricePerNightAud=95, nights=5, priceNote='from ~US$84', checkIn='2027-02-11', checkOut='2027-02-16', distance='Central', url='https://www.momondo.com/hotels/nozawaonsen', notes='Confirm it is a private room, not a dorm, before booking.'),
  dict(id='s-nz9', name='Mid-range ryokan with dinner and breakfast (Kawamotoya, Nozawa View Hotel Shimataka)', town='Nozawa Onsen', type='Ryokan, half board', status='planned', pricePerNightAud=165, nights=5, priceNote='¥15,000-19,000 pp half board est.; verify', checkIn='2027-02-11', checkOut='2027-02-16', distance='5-8 min to the gondola', url='https://travel.rakuten.com/', notes='Planned as the budget placeholder until something is booked. A ryokan dinner is the local-cuisine experience you asked for and solves the solo-dinner question. Search these on Rakuten Travel with 1 adult.'),
  # Fallbacks if Nozawa is full
  dict(id='s-tg1', name='Togari Onsen pension (fallback, 20 min bus from Nozawa)', town='Togari Onsen (fallback)', type='Small pensions and minshuku', status='idea', pricePerNightAud=100, nights=5, priceNote='cheaper than Nozawa; verify', checkIn='2027-02-11', checkOut='2027-02-16', distance='Across the valley from Nozawa; direct bus to Nozawa 20 min, Iiyama Station 30 min', url='https://togari-onsen.com/', notes='Quiet little ski village with its own small resort. If Nozawa is truly full, sleep here and bus over for the Nozawa ski days. Fewer restaurants; more Japanese.'),
  dict(id='s-my1', name='Akakura Hotel (Myoko, accepts solo bookings)', town='Myoko Kogen (alternative base)', type='Onsen hotel', status='idea', pricePerNightAud=120, nights=5, priceNote='verify on Rakuten', checkIn='2027-02-11', checkOut='2027-02-16', distance='Akakura Onsen village, walk to lifts', url='https://travel.rakuten.com/usa/en-us/hotel_info_item/cnt_japan/sub_niigata_prefecture/cty_myoko_city/10123456871361', notes='Explicitly takes reservations from one person. Also on Rakuten: Kounkaku (grand old ryokan), Kotobukiro, Hotel Takeda. Switching base changes only the Nagano end of the plan.'),
]

food = [
  dict(id='fd1', town='Nozawa Onsen', dish='Nozawana (pickled turnip greens)', where='Every meal; buy a bag from a village grandma’s shop to take home', why='The village’s signature food. Every family pickles its own; you will be offered it constantly.', priceBand='¥'),
  dict(id='fd2', town='Nozawa Onsen', dish='Oyaki', where='Street stalls near Oyu and at Nagano Station', why='Grilled-then-steamed buns filled with nozawana, pumpkin or bean paste. The Nagano snack.', priceBand='¥'),
  dict(id='fd3', town='Nozawa Onsen', dish='Shinshu soba at Sobadokoro Daimon', where='Main street, 100+ years in the Katagiri family', why='Hand-cut buckwheat noodles, cold zaru style with dipping sauce. Old shop, no fuss.', priceBand='¥¥'),
  dict(id='fd4', town='Nozawa Onsen', dish='Basashi (horse sashimi)', where='Any village izakaya', why='Nagano speciality, served with ginger and soy. Try it once.', priceBand='¥¥'),
  dict(id='fd5', town='Nozawa Onsen', dish='Onsen tamago from the Ogama', where='Ogama, top of the village', why='Eggs slow-cooked in the 90°C spring. Locals cook their vegetables there too; it is the village kitchen.', priceBand='¥'),
  dict(id='fd6', town='Nozawa Onsen', dish='Set dinner at Wakagiri', where='Main street', why='Home-style teishoku that locals actually eat. Not a ski-bar.', priceBand='¥¥'),
  dict(id='fd7', town='Osaka', dish='Okonomiyaki at a neighbourhood counter', where='Any counter with a hotplate in Fukushima or Tenma (avoid the Dotonbori queues)', why='Osaka’s home cooking. Sit at the teppan, order “buta-tama”, watch it made.', priceBand='¥'),
  dict(id='fd8', town='Osaka', dish='Doteyaki and kushikatsu in Tenma', where='Izakaya alleys under the tracks at Tenma station', why='Beef tendon simmered in miso, and the deep-fried skewers Osaka is known for, in the part of town where office workers drink. No double dipping.', priceBand='¥'),
  dict(id='fd9', town='Osaka', dish='Takoyaki from a street stand', where='A stand with a queue of locals, not the ones with English menus', why='Octopus balls, Osaka’s thing. Eat them standing up, straight away.', priceBand='¥'),
  dict(id='fd10', town='Osaka', dish='Kitsune udon', where='Usami-tei Matsubaya (the shop that claims to have invented it, near Minami-Semba)', why='Udon in dashi with sweet fried tofu, Osaka’s soul food. Old shop, cheap.', priceBand='¥'),
  dict(id='fd11', town='Osaka', dish='Yakiniku in Tsuruhashi (Korea Town)', where='Tsuruhashi station area', why='Osaka’s Korean neighbourhood; smoky yakiniku joints, nothing trendy about it. Good for a solo counter seat.', priceBand='¥¥'),
  dict(id='fd15', town='Osaka', dish='Kushikatsu at Yaekatsu (Shinsekai)', where='Shinsekai, a few doors from the famous Daruma', why='If you do go to Shinsekai, this is the locals’ pick over the tourist-famous Daruma. About ¥2,000 a head.', priceBand='¥'),
  dict(id='fd16', town='Osaka', dish='Fukushima izakaya under the tracks', where='Fukumaru-dori, one Loop Line stop from Osaka Station', why='A workers’ dining street lined with small izakaya and bars; a good alternative base for dinner if the hotel is around Fukushima.', priceBand='¥¥'),
  dict(id='fd12', town='On the way', dish='Ekiben (station bento)', where='Ekibenya Matsuri, Tokyo Station', why='Regional lunch boxes to eat on the Shinkansen. Pick one from Nagano or Niigata.', priceBand='¥'),
  dict(id='fd13', town='Nagano', dish='Shinshu miso ramen', where='Nagano Station area', why='Nagano is miso country. Warm you up after the Shinano train.', priceBand='¥'),
  dict(id='fd14', town='USJ', dish='Kinopio’s Cafe', where='Super Nintendo World', why='The one touristy meal that is worth it: themed, and you are already inside.', priceBand='¥¥'),
]

budget = [
  dict(id='bg1', category='Parking', label='Brisbane Airport AIRPARK, 9 days', amount=119, currency='AUD', status='estimate', notes='A$99/week + A$10/day. Book online; sometimes cheaper than drive-up. MCY would be ~A$90 but needs a A$55-85 shuttle back from Brisbane on the way home.'),
  dict(id='bg2', category='Transport', label='Fuel Gympie ↔ Brisbane Airport', amount=65, currency='AUD', status='estimate', notes='~167 km each way.'),
  dict(id='bg3', category='Insurance', label='Travel insurance with snow-sports cover, 10 days', amount=130, currency='AUD', status='estimate', variant='ski', notes='Must include skiing. Medicare does not cover Japan.'),
  dict(id='bg3b', category='Insurance', label='Travel insurance, 10 days (no snow sports needed)', amount=90, currency='AUD', status='estimate', variant='culture', notes='Medicare does not cover Japan.'),
  dict(id='bg4', category='Connectivity', label='eSIM, 10 days data', amount=30, currency='AUD', status='estimate', notes='Ubigi or Airalo; install before you leave.'),
  dict(id='bg5', category='Food', label='Breakfasts, snacks, drinks, incidentals (¥3,000/day x 8)', amount=24000, currency='JPY', status='estimate'),
  dict(id='bg6', category='Other', label='Onsen towels, ski socks, souvenirs, contingency', amount=200, currency='AUD', status='estimate'),
  dict(id='bg7', category='Transport', label='Suica top-ups (local trains, buses, vending machines)', amount=5000, currency='JPY', status='estimate'),
  dict(id='bg8', category='Activities', label='USJ Express Pass 4 with Super Nintendo World entry (optional but recommended)', amount=12800, currency='JPY', status='estimate', notes='Nintendo-inclusive Express Pass 4 variants (e.g. “Mine Cart & Jaws”) were ~¥12,800 in 2026; Express Pass 7 ¥17,800-21,800. Names change every season: buy any Express Pass whose description includes “Super Nintendo World Area Entry” (ideally with Mario Kart and Mine-Cart Madness). Sells out on popular dates.'),
]

checklist = [
  dict(id='ck1', group='Before you go', text='Check what your two lounge passes actually are: Qantas app → Complimentary Lounge Invitations → type (Titanium / Platinum One / General / Domestic) and expiry', due='2026-09-30', done=True, notes='Only Titanium or Platinum One invitations open the Melbourne First Lounge. General/Domestic ones add nothing on this trip because the Business ticket already covers the Business lounges.'),
  dict(id='ck2', group='Points and bookings', text='Keep a free AwardFares alert on QF62 NRT→BNE and QF80 NRT→MEL for 16 Feb 2027 (Business especially)', due='2026-09-20', notes='Seats are released in batches. The paid Sale fare cannot be upgraded, but a Business Classic Reward could replace it if one appears and the Sale fare’s cancellation terms make it worthwhile (Sale fares are usually non-refundable, so probably not).'),
  dict(id='ck3', group='Points and bookings', text='Book Nozawa Onsen accommodation for 11-16 Feb, 5 nights (long weekend; the village sells out)', due='2026-09-30', notes='Email the minshuku directly for a single room, or Booking.com. Ask about single-occupancy pricing and whether dinner is included.'),
  dict(id='ck4', group='Points and bookings', text='Book Osaka hotel for 9-11 Feb', due='2026-10-31', notes='Toyoko Inn / Dormy Inn open bookings ~3-6 months ahead. Free cancellation where possible.'),
  dict(id='ck5', group='Points and bookings', text='Book the flight home', due='2026-09-13', done=True, notes='Done: QF80 + QF1256, Tue 16 Feb, paid Economy Sale fare, one booking. Add the booking reference to the Private vault, not here.'),
  dict(id='ck6', group='Points and bookings', text='Book the Brisbane → Sydney feeder', due='2026-09-13', done=True, notes='Done: JQ815, 8 Feb, 09:45-12:20, Classic Reward.'),
  dict(id='ck5b', group='Points and bookings', text='Open Manage Booking for QF80 and try to add Economy Plus (extra legroom) with cash or points; pick seats on both flights', due='2026-09-30', notes='Sale fares cannot be upgraded to Business with points, but the Economy Plus seat product is separate. If it is not offered on this fare, that is that.'),
  dict(id='ck5c', group='Coming home', text='Melbourne: 1h35 connection. SmartGate, bag, customs, domestic transfer desk, T1. Skip duty free.', due='2027-02-17'),
  dict(id='ck6b', group='Points and bookings', text='Check the JQ815 booking shows a 20 kg checked bag (reward bookings include one, but the confirmation sometimes shows 0 kg); add a bag if not', due='2026-09-30'),
  dict(id='ck6c', group='Before you go', text='Check in online for QF481 the day before (24 h out) so Sydney is bag-drop only', due='2027-02-07'),
  dict(id='ck7', group='Points and bookings', text='Book Brisbane AIRPARK online for 8-17 Feb', due='2026-11-30'),
  dict(id='ck8', group='Points and bookings', text='Buy USJ 1-Day Studio Pass + Express Pass 4 with Super Nintendo World entry for Wed 10 Feb (dates open 60 days ahead, so ~12 Dec 2026)', due='2026-12-12', notes='Official USJ site or Klook (official partner; Klook lets you move the date within 90 days in the same price tier). Buy the day it opens. Create the USJ app account now: since Jan 2026 the app is mandatory for timed-entry tickets.'),
  dict(id='ck9', group='Points and bookings', text='Travel insurance with the snow-sports add-on (and off-piste cover if you plan to ski Nozawa’s tree runs)', due='2026-11-30', notes='Standard Australian policies exclude skiing. About A$80 for a week before the add-on. Buy it when you book the first non-refundable thing so cancellation cover starts. Medicare does not cover Japan.'),
  dict(id='ck10', group='Points and bookings', text='Reserve Shinkansen and Shinano seats (smart-EX for Tokyo↔Osaka, JR East site for Hokuriku), opens 1 month before each travel date', due='2027-01-09', notes='9 Jan for the 9 Feb trains; 11 Jan for the 11 Feb trains; 16 Jan for the 16 Feb trains. Holiday Thursday trains fill.'),
  dict(id='ck11', group='Before you go', text='Register on Visit Japan Web (immigration + customs QR)', due='2027-01-20', notes='Australians get 90 days visa-free. Passport just needs to be valid for the stay, but check the expiry anyway.'),
  dict(id='ck12', group='Before you go', text='Install eSIM (Ubigi ~US$14 for 10 GB/7 days, or Airalo) and set up Welcome Suica Mobile (iPhone) or plan to buy a physical Welcome Suica at Narita (Android)', due='2027-01-31', notes='Suica works in Osaka (ICOCA area) and Nagano too. Google Wallet on non-Japanese Android phones generally cannot hold Suica; the physical Welcome Suica is cash top-up only and expires after 28 days, which is fine for this trip. Top up with Mastercard/Amex in Apple Wallet; some Visa cards fail.'),
  dict(id='ck13', group='Before you go', text='Re-check Melbourne T2 lounge hours for Monday nights (Business Lounge and, if your passes qualify, First Lounge)', due='2027-01-31'),
  dict(id='ck14', group='Before you go', text='Tell your bank you are travelling; get ¥30,000-50,000 cash (or plan to withdraw at 7-Eleven ATMs on arrival)', due='2027-02-01', notes='Ski villages and small restaurants are still cash-heavy.'),
  dict(id='ck15', group='Before you go', text='Book ski rental online (village shop) for Fri 12, Sat 13, Mon 15 and Tue 16 morning with your boot size in cm; include ski wear if travelling light', due='2027-01-15', notes='Big boot sizes run out in peak weeks. Pick a shop that opens by 7:45 so Friday is not lost.'),
  dict(id='ck16', group='Packing', text='Ski: thermals, mid-layer, gloves, goggles, beanie, buff, ski socks x3 (rent jacket/pants/skis/boots/helmet)', due='2027-02-06'),
  dict(id='ck17', group='Packing', text='Onsen kit: small towel, plus a sense of humour about being naked with strangers', due='2027-02-06'),
  dict(id='ck18', group='Packing', text='Carry-on for the plane: passport, printed e-ticket, USJ tickets, chargers, Type-A power adapter (Japan is 100 V, US-style plugs), snacks', due='2027-02-07'),
  dict(id='ck19', group='In Japan', text='USJ: through the gate, open the app, claim Super Nintendo World timed entry within seconds (or use the Express Pass slot)', due='2027-02-10'),
  dict(id='ck20', group='In Japan', text='Keep the N’EX round-trip ticket somewhere safe for the trip back to Narita', due='2027-02-09'),
  dict(id='ck23', group='In Japan', text='Tax-free shopping is now a refund at the airport (from Nov 2026): pay the 10% tax at the till, keep receipts and passport scans, and allow time at Narita to claim it back on Nintendo World or Osaka souvenirs', due='2027-02-16'),
  dict(id='ck24', group='Before you go', text='Open the Qantas app → Complimentary Lounge Invitations and confirm the Titanium First Lounge invitations show with an expiry after 8 Feb 2027', due='2026-09-30', notes='They renew each card anniversary. If the current pair expires before February, the next pair will be issued on the anniversary; check which.'),
  dict(id='ck25', group='Points and bookings', text='Ask the Nozawa lodging (when booking) whether they accept a courier parcel before arrival, and get their address in Japanese for the takkyubin slip', due='2026-10-31'),
  dict(id='ck26', group='Points and bookings', text='Reserve the Shinano seats Nagoya → Kiso-Fukushima and Shiojiri → Nagano for Thu 11 Feb, plus the local train times to and from Narai', due='2027-01-11', notes='Holiday Thursday: reserved seats go. The local Chuo line runs roughly hourly, so match the connections when you book.'),
  dict(id='ck27', group='Before you go', text='Buy simple strap-on crampons (or plan to buy at Workman/Don Quijote in Osaka) for the Togakushi snow walk', due='2027-02-01'),
  dict(id='ck28', group='In Japan', text='Saturday night: check Sunday’s weather. Powder dump = ski; anything else = Togakushi. Check the Alpico winter bus 70 timetable for the first bus and the last bus back', due='2027-02-13'),
  dict(id='ck21', group='Coming home', text='Return rental gear; settle the lodging bill in cash if they do not take cards', due='2027-02-16'),
  dict(id='ck22', group='Coming home', text='Narita T2 check-in closes 18:20 for QF80 (check in online the day before)', due='2027-02-16'),
]

places = [
  dict(id='p1', name='Gympie (home)', kind='town', town='Queensland', lat=-26.19, lng=152.665),
  dict(id='p2', name='Brisbane Airport (BNE)', kind='airport', town='Brisbane', lat=-27.3842, lng=153.1175, notes='AIRPARK long stay, free shuttle.'),
  dict(id='p3', name='Sunshine Coast Airport (MCY)', kind='airport', town='Marcoola', lat=-26.6033, lng=153.0910, notes='Alternative departure airport. No lounge.'),
  dict(id='p4', name='Sydney Airport T3', kind='airport', town='Sydney', lat=-33.9399, lng=151.1753, notes='Qantas domestic. Business Lounge opposite gates 4-5.'),
  dict(id='p5', name='Melbourne Airport T2', kind='airport', town='Melbourne', lat=-37.6690, lng=144.8410, notes='International. Business Lounge level 1, First Lounge level 3.'),
  dict(id='p6', name='Narita Airport T2', kind='airport', town='Narita', lat=35.7720, lng=140.3929, notes='Arrive 9 Feb, depart 15 Feb.'),
  dict(id='p7', name='Tokyo Station', kind='station', town='Tokyo', lat=35.6812, lng=139.7671, notes='N’EX arrives here; Shinkansen to Osaka and Nagano.'),
  dict(id='p8', name='Shin-Osaka Station', kind='station', town='Osaka', lat=34.7335, lng=135.5002),
  dict(id='p9', name='Universal Studios Japan', kind='park', town='Osaka', lat=34.6654, lng=135.4323, notes='Super Nintendo World. Universal City station is 5 min walk.'),
  dict(id='p10', name='Tenma / Tenjinbashisuji', kind='food', town='Osaka', lat=34.7043, lng=135.5133, notes='Izakaya alleys and the long arcade.'),
  dict(id='p11', name='Nakazakicho', kind='town', town='Osaka', lat=34.7090, lng=135.5060, notes='Old lanes, small cafes, 10 min from Umeda.'),
  dict(id='p25', name='Nintendo OSAKA (Daimaru Umeda 13F)', kind='other', town='Osaka', lat=34.7020, lng=135.4980),
  dict(id='p19', name='Fukushima (Osaka) dining street', kind='food', town='Osaka', lat=34.6960, lng=135.4870, notes='Fukumaru-dori under the Loop Line tracks.'),
  dict(id='p20', name='Tsuruhashi (Korea Town) yakiniku', kind='food', town='Osaka', lat=34.6650, lng=135.5320, notes='Tsuruichi (1949), Aji Yoshi, Horumon Sora.'),
  dict(id='p21', name='Narai-juku', kind='town', town='Kiso valley', lat=35.9670, lng=137.8100, notes='Edo-period post town on the Nakasendo. Bag-minding at the station ¥300.'),
  dict(id='p22', name='Kiso-Fukushima Station', kind='station', town='Kiso valley', lat=35.8420, lng=137.6930, notes='Shinano stops here; change to the local train for Narai.'),
  dict(id='p23', name='Togakushi Okusha (inner shrine) entrance', kind='other', town='Togakushi', lat=36.7620, lng=138.0870, notes='Start of the cedar avenue; winter bus stop.'),
  dict(id='p24', name='Zenko-ji temple', kind='other', town='Nagano', lat=36.6617, lng=138.1876, notes='Get off bus 70 at Zenkoji Daimon.'),
  dict(id='p12', name='Nagoya Station', kind='station', town='Nagoya', lat=35.1709, lng=136.8815, notes='Change from Nozomi to the Shinano limited express.'),
  dict(id='p13', name='Nagano Station', kind='station', town='Nagano', lat=36.6431, lng=138.1887, notes='Soba and oyaki in the station.'),
  dict(id='p14', name='Iiyama Station', kind='station', town='Iiyama', lat=36.8500, lng=138.3600, notes='Nozawa Onsen Liner bus leaves from here.'),
  dict(id='p15', name='Nozawa Onsen village', kind='town', town='Nozawa Onsen', lat=36.9230, lng=138.4420, notes='13 free bathhouses; Oyu in the centre.'),
  dict(id='p16', name='Nozawa Onsen Snow Resort (Nagasaka gondola)', kind='resort', town='Nozawa Onsen', lat=36.9190, lng=138.4470, notes='297 ha, 1,085 m vertical.'),
  dict(id='p17', name='Akakura Onsen (Myoko), alternative base', kind='resort', town='Myoko', lat=36.8830, lng=138.1600, notes='Runner-up option: quieter, cheaper, deeper snow, smaller mountain.'),
  dict(id='p18', name='Hakuba Happo-One, alternative', kind='resort', town='Hakuba', lat=36.6980, lng=137.8320, notes='Biggest terrain, most international.'),
]

questions = [
  dict(id='q1', question='Ski base: Nozawa Onsen, Myoko (Akakura Onsen) or Hakuba?', why='You said “south island”, which does not exist for skiing (Japan’s ski areas are on Hokkaido in the north and in the Nagano/Niigata mountains on the main island). Given Narita arrival + Osaka + a week, Nagano/Niigata is the only sensible region. Nozawa is the closest thing to Banff: a real village, walkable, hot springs, mountain rising straight off it, local food. It is also the most Australian of the villages and the busiest over the 11-14 Feb long weekend.', options=['Nozawa Onsen (planned): Banff-like village, big mountain, local food, busiest and priciest of the three that weekend', 'Myoko / Akakura Onsen: quieter, cheaper, more Japanese, 13-16 m of snow, smaller mountain, fiddlier buses', 'Hakuba: biggest terrain and most Banff-like scale, but a sprawl of villages linked by buses and very international'], recommendation='Nozawa Onsen. If you decide “not hyped” matters more than terrain, switch to Myoko: the plan only changes at the Nagano end (Shinkansen to Joetsu-Myoko instead of Iiyama).', answer='Nozawa sounds good', resolved=True),
  dict(id='q2', question='Trip shape: Universal Studios first (Wednesday) or ski first and fly home from Osaka?', why='Wed 10 Feb is the only calm weekday for USJ in the window (Thu 11 is a public holiday and the weekend follows, plus the tail of Lunar New Year travel). That forces the skiing onto the long weekend. The alternative is ski Wed-Fri (quieter slopes on Wed), then USJ on Mon 15 and fly Jetstar Osaka → Brisbane at 9:45pm that night, no Tokyo backtrack.', options=['USJ Wed 10, ski Fri-Mon, fly QF62 Narita → Brisbane Mon 15 (planned)', 'Ski Wed-Fri, Osaka Sat-Mon, USJ Mon 15, Jetstar JQ24 Osaka → Brisbane Mon 15 night'], recommendation='Keep USJ on the Wednesday. Super Nintendo World on a crowded day is the thing most likely to spoil the trip, and Nozawa is big enough to absorb a weekend if you start at 8:30. Monday morning skiing is the bonus.', answer='Ok sounds good. (And the flight home is now booked out of Narita, so ending in Osaka is no longer possible.)', resolved=True),
  dict(id='q3', question='Park at Brisbane or Sunshine Coast?', why='Decided by the booking: JQ815 departs Brisbane, and QF62 lands there. AIRPARK for 8-16 Feb.', options=['Brisbane (booked)'], recommendation='Brisbane.', answer='Ok sounds good. JQ815 booked 8 Feb 09:45.', resolved=True),
  dict(id='q4', question='How to use the points for the flight home?', why='Overtaken by events: QF62 had no reward seats, and QF80 + QF1256 was booked as a paid Economy Sale fare (¥92,570). Sale fares cannot be upgraded with points.', options=['Add Economy Plus extra legroom on QF80 in Manage Booking (cash or ~19,500 pts) if it is offered', 'Keep the ~164k points for the next trip'], recommendation='Try Economy Plus; otherwise bank the points.', answer='Booked cash Economy Sale on QF80 + QF1256.', resolved=True),
  dict(id='q5', question='What are the two “first class lounge passes”, exactly?', why='Answered: they are Qantas Money Titanium card First Lounge invitations. Valid at the Sydney, Melbourne and LA First Lounges on a QF/JQ flight, cardholder only.', options=['Use one at Melbourne T2 First Lounge on 8 Feb', 'Second one is unusable on this trip; keep it'], recommendation='Use one in Melbourne on 8 Feb; check the expiry in the Qantas app.', answer='Titanium credit card passes. One will be used in Melbourne; the other saved.', resolved=True),
  dict(id='q6', question='Rent ski gear or bring your own?', why='Rental in Nozawa is ~¥4,450-5,500 a day for skis, boots and poles, so 4 days is about A$165-200. Bringing skis means a 32 kg-allowance bag on the outbound (fine in Business) but hauling it through Tokyo Station, Osaka and two bus changes, plus the Shinkansen oversized-baggage rule.', options=['Rent everything in the village, bring only boots if you love yours (planned)', 'Bring skis and boots'], recommendation='Rent. This trip has too many trains for a ski bag. Bring your own boots only if fit is a problem for you.', answer='Rent in the village. The suitcase goes by courier and the itinerary has no room for a ski bag.', resolved=True),
  dict(id='q7', question='Fly home Monday 15 or Tuesday 16 Feb?', why='Decided: Tuesday 16. Monday becomes a full quiet ski day; the extra day costs about A$900 all-in.', options=['Tue 16: QF80 + QF1256 via Melbourne (booked)'], recommendation='Done.', answer='Tuesday 16 Feb, QF80 + QF1256 booked.', resolved=True),
  dict(id='q8', question='Keep this repo public?', why='The repo is public right now. That is why the app never writes booking references, ticket numbers or passport details to the repo (they live in the Private vault on your device). It is still safer to make the repo private since GitHub Pages works on private repos with a paid plan, or you can simply keep the rule: nothing sensitive in the plan text.', options=['Keep public, keep sensitive details in the vault only (current)', 'Make the repo private (Settings → General → Danger zone). Pages on private repos needs GitHub Pro.'], recommendation='Keep public for now and use the vault; revisit if you want to store confirmation emails in the repo.', answer='Keep public; sensitive details stay in the vault.', resolved=True),
  dict(id='q10', question='Give up Sunday’s skiing for Togakushi and Zenko-ji, or fly home Tuesday to keep three full ski days?', why='You asked for a rural day and said a ski day could go. Narai-juku is now built into Thursday’s travel day at no cost. Sunday is the worst ski day (long-weekend crowds), so it is the cheapest one to trade for Togakushi’s cedar avenue and Zenko-ji. That leaves Friday, Saturday and Monday morning on skis. Flying home Tuesday 16 instead would add a full quiet Monday on the slopes for about A$150 of lodging plus a day of leave.', options=['Sunday rural day, Monday morning ski, fly Mon 15 (planned)', 'Sunday rural day and fly Tue 16 so Monday is a full ski day', 'Keep skiing Sunday; rural Japan is just the Narai stop on Thursday'], recommendation='As planned, with the powder-day escape hatch: if Sunday dawns dumping, ski and skip Togakushi.', answer='Tue 16 is booked, so Monday is a full ski day and Sunday is the rural day, with the powder-day swap written into Sunday’s notes.', resolved=True),
  dict(id='q11', question='Which rural stop, if you want a different one?', why='Alternatives to Togakushi from Nozawa: Obuse (30 min from Nagano by Nagaden train, chestnut sweets, the Hokusai museum, sake brewery, old streets; easy and flat) or a dawn visit to Zenko-ji’s o-asaji morning service. Shirakawa-go’s farmhouses are the postcard but are 4+ hours each way from Nozawa and heavily touristed; not worth it on this trip. Matsumoto castle is a city.', options=['Togakushi + Zenko-ji (planned): mountain shrine, cedars, soba, snow walk', 'Obuse + Zenko-ji: gentler, indoor-heavy, good if the weather is foul', 'Nothing beyond Narai'], recommendation='Togakushi, with Obuse as the bad-weather substitute.', answer='Togakushi and Zenko-ji, with Obuse as the foul-weather substitute. Decide on the Saturday night.', resolved=True),
  dict(id='q9', question='Rough budget ceiling?', why='The plan currently totals roughly A$2,700-3,300 in cash on top of points, depending on Osaka hotel and the Express Pass. Knowing your ceiling decides whether to trade the ryokan half-board for a minshuku, and whether the Express Pass stays in.', options=['Under A$2,500: minshuku, skip Express Pass, Jetstar home', 'A$2,500-3,500: as planned', 'Over A$3,500: ryokan with dinner every night, Business home if available'], recommendation='As planned. The Express Pass is the one “splurge” that buys back a whole day.', answer='', resolved=False),
]

FOOD_GUIDE = [
  dict(title='How to tell a place is happy to have you', body='Green lights: a menu or prices visible outside, a ticket machine (ramen, soba, gyudon), plastic food models, a photo or English menu, a listing on Tabelog, staff who call “irasshaimase” when the door opens, and any yakiniku, okonomiyaki, udon or soba shop. Nozawa, Tenma, Fukushima, Tsuruhashi and Narai are all used to visitors; you are not intruding.'),
  dict(title='When to bow out', body='A sign reading 一見さんお断り (ichigen-san okotowari, “first-timers not accepted”) or 会員制 (members only); a tiny “snack” bar with a hostess and no price list; a six-seat counter where every seat is a regular and the master does not look up. Being turned away is not an insult: a small bow, “sumimasen”, and try the next door. That system is mostly Kyoto tea-house culture anyway; Osaka standing bars welcome anyone who orders a drink.'),
  dict(title='Manners that matter more than language', body='Order a drink first, then food. The small dish that arrives unasked (otoshi) is a cover charge, not a mistake. One drink and a couple of plates, then move on when it is crowded; angle your body to make room at a standing bar. Cash out, no tipping ever. No photos of other customers or the counter without a nod from the master. “Oishii” and “gochisosama deshita” (thanks for the meal) on the way out go a long way.'),
  dict(title='Onsen and ryokan', body='Shoes off at the genkan, slippers off on tatami. Ryokan dinner is at a set time; be there. In the bathhouses: wash sitting down before you get in, no towel in the water, no swimwear, quiet, no phones. Tattoos: Nozawa’s village bathhouses are relaxed but cover-up stickers are cheap insurance if you have visible ink.'),
]

STAYS_GUIDE = [
  dict(title='Why Booking.com looks empty', body='Booking.com carries maybe a third of Nozawa’s beds, and Japanese inns often list only twin rooms at a 2-person price, which makes a solo search show “sold out” or silly prices. Peak weeks (this is one) also get released to Japanese sites first.'),
  dict(title='Where the rooms actually are', body='1. Rakuten Travel (travel.rakuten.com, English) and Jalan: search with 1 adult; they show single-occupancy plans with meals. 2. Email the inn directly in short simple English: dates, one person, one room, ask the price with breakfast. Most reply within a day. 3. Nozawa Holidays (nozawaholidays.com) manages a dozen lodges and will answer one email with everything that still has a solo room. 4. Stay Nozawa and nozawaonsen.ski run request forms that go to several properties at once.'),
  dict(title='What to ask for', body='“1 person, single occupancy, 11-16 Feb, private room, breakfast included if possible.” Expect a supplement of 20-30% over the per-person twin rate. Shared bathrooms are normal and fine: you will be in the village bathhouses anyway.'),
  dict(title='If it is truly full', body='Togari Onsen is 20 minutes by bus across the valley and much quieter and cheaper; sleep there and bus to Nozawa for skiing. Or switch base to Akakura Onsen (Myoko), where several ryokan take single bookings on Rakuten; only the Nagano end of the plan changes. Iiyama Station has very little lodging, so do not count on it.'),
]


# =============================================================================
# PLAN B: no skiing. Same flights, same Osaka/USJ days; then Koyasan, Takayama,
# Shirakawa-go, Matsumoto and Narai. Tag everything ski-specific as 'ski' and
# everything below as 'culture'; untagged content belongs to both.
# =============================================================================
SKI_DAYS = {'2027-02-11', '2027-02-12', '2027-02-13', '2027-02-14', '2027-02-15', '2027-02-16'}
SHARED_16 = {'j6', 'j7', 'j8'}
for d in days:
    if d['date'] in SKI_DAYS:
        for it in d['items']:
            if not (d['date'] == '2027-02-16' and it['id'] in SHARED_16):
                it['variant'] = 'ski'

B_DAYS = {
  '2027-02-11': dict(title='Osaka → Koyasan (temple lodging)', base='Koyasan shukubo', notes='National Foundation Day. Koyasan is a 1,200-year-old monastery town on a forested plateau, 2 hours from Namba: 117 temples, a 2 km cemetery walk through giant cedars, and a night in a temple with the monks’ vegetarian dinner. In February it is cold and often snowy, which is exactly when it is at its best and quietest. Travel with a daypack; the suitcase went ahead on Tuesday.'),
  '2027-02-12': dict(title='Morning prayers, then Koyasan → Takayama', base='Takayama', notes='Long travel day through three regions: down the mountain, Shinkansen to Nagoya, then the Hida express up the gorge to Takayama, an old merchant town in the mountains with sake breweries and morning markets.'),
  '2027-02-13': dict(title='Takayama → Shirakawa-go farmhouse night', base='Shirakawa-go gassho farmhouse', notes='Shirakawa-go’s thatched gassho-zukuri farmhouses under two metres of snow are the picture everyone has in their head of rural Japan. It is heavily visited from 10 to 3; sleeping in one of the farmhouses means you have the village to yourself at dusk and dawn. No light-up event in Feb 2027 (they were in January), so normal bookings apply.'),
  '2027-02-14': dict(title='Shirakawa-go → Takayama → over the Alps to Matsumoto', base='Matsumoto', notes='Quiet dawn in the village, a last look at Takayama, then the winter express bus over the Northern Alps via Hirayu Onsen (reservations mandatory) to Matsumoto, home of Japan’s finest original castle.'),
  '2027-02-15': dict(title='Matsumoto Castle and the Narai post town', base='Matsumoto', notes='Castle first thing before the tour buses, then an hour on local trains to Narai-juku, the best-preserved Edo post town on the old Nakasendo road, and back for a soba dinner. Optional onsen at Asama in the evening.'),
  '2027-02-16': dict(title='Matsumoto → Tokyo → home', base='Overnight flight', notes='The Azusa express runs straight to Shinjuku in about 2h30; the Narita Express leaves from Shinjuku too, so there is no fiddling around in Tokyo. QF80 check-in closes 18:20.'),
}
B_ITEMS = {
  '2027-02-11': [
    item('c11a', '08:30', 'transfer', 'Check out (daypack only), subway to Namba', location='Osaka → Nankai Namba station', cost=300, currency='JPY'),
    item('c11b', '09:10', 'train', 'Nankai to Gokurakubashi, cable car, bus into town', location='Nankai Namba → Gokurakubashi (Limited Express Koya ~80 min, or express with a change at Hashimoto ~100 min) → cable car 5 min → bus 10 min to Senjuinbashi', endTime='11:15', cost=3980, currency='JPY', notes='Buy the Koyasan World Heritage Ticket at Namba (~¥3,980): return train, cable car and unlimited Koyasan buses for two days. Reserve the limited express seat for the holiday.'),
    item('c11c', '11:30', 'food', 'Lunch near Senjuinbashi: soba, udon or a shojin set', location='Main street, Koyasan', cost=1300, currency='JPY'),
    item('c11d', '12:30', 'activity', 'Danjo Garan (the great pagoda) and Kongobuji head temple', location='Central Koyasan', endTime='14:30', cost=1700, currency='JPY', notes='Kongobuji has the largest rock garden in Japan and painted sliding doors; Konpon Daito is the vermilion pagoda. Bus or 15 min walk between them.'),
    item('c11e', '14:30', 'stay', 'Check in at the shukubo (temple lodging)', location='See Stays: Ekoin, Fukuchiin or Shojoshin-in', notes='Tatami room, shared baths, dinner served in your room by monks-in-training. Curfew around 9pm. Solo guests are normal here.'),
    item('c11f', '15:30', 'activity', 'Okunoin cemetery walk to Kobo Daishi’s mausoleum', location='Ichinohashi bridge → Okunoin (2 km, flat)', endTime='17:00', cost=0, currency='JPY', notes='200,000 graves under thousand-year cedars, lanterns, snow. The single most atmospheric walk in Japan. Photography stops at the last bridge; go quiet there.'),
    item('c11g', '17:30', 'food', 'Shojin ryori dinner at the temple', location='Your room', cost=0, currency='JPY', notes='Vegetarian Buddhist cuisine: sesame tofu (goma-dofu, the Koyasan speciality), mountain vegetables, tempura. Included in the lodging price.'),
    item('c11h', '19:00', 'activity', 'Okunoin night tour with a monk (optional)', location='Departs Ekoin', endTime='20:30', cost=3000, currency='JPY', status='idea', notes='Ekoin runs an English-language night walk most evenings; other temples can book you on it.'),
  ],
  '2027-02-12': [
    item('c12a', '06:30', 'activity', 'Morning prayers and the goma fire ritual', location='Temple main hall', endTime='07:30', cost=0, currency='JPY', notes='Guests sit at the back. Then breakfast in your room.'),
    item('c12b', '09:00', 'transfer', 'Bus, cable car and Nankai back to Namba, subway to Shin-Osaka', location='Koyasan → Nankai Namba → Shin-Osaka', endTime='11:45', cost=300, currency='JPY', notes='Return leg is covered by the World Heritage Ticket; the subway hop is ¥300.'),
    item('c12c', '12:10', 'train', 'Nozomi Shin-Osaka → Nagoya', location='Shin-Osaka', endTime='13:00', cost=6880, currency='JPY'),
    item('c12d', '13:15', 'food', 'Quick lunch at Nagoya Station', location='Nagoya', cost=1200, currency='JPY', notes='Miso-katsu or a kishimen noodle stand on the platform, the Nagoya things.'),
    item('c12e', '13:45', 'train', 'Limited Express Hida Nagoya → Takayama', location='Nagoya', endTime='16:15', cost=6500, currency='JPY', notes='~2h30 up the Hida river gorge; reserved seat. One of the scenic rides.'),
    item('c12f', '16:30', 'stay', 'Check in, Takayama (1 night)', location='See Stays'),
    item('c12g', '17:15', 'activity', 'Sanmachi old town at dusk, sake breweries', location='Sanmachi Suji, 10 min walk from the station', endTime='18:30', cost=0, currency='JPY', notes='Edo-period merchant streets. The breweries with cedar balls hanging outside do tastings for a few hundred yen.'),
    item('c12h', '19:00', 'food', 'Hida beef dinner', location='A local grill or hoba-miso restaurant off the main drag', cost=4000, currency='JPY', notes='Hida beef on a magnolia leaf with miso (hoba-miso) is the dish. Skip the ones with touts.'),
  ],
  '2027-02-13': [
    item('c13a', '07:30', 'food', 'Miyagawa morning market', location='Riverbank, Takayama', cost=800, currency='JPY', notes='Farmers, pickles, mitarashi dango (soy-glazed rice dumplings) for breakfast.'),
    item('c13b', '08:50', 'bus', 'Nohi bus Takayama → Shirakawa-go', location='Takayama Nohi Bus Center (next to the station)', endTime='09:40', cost=1800, currency='JPY', notes='50 min. Reserve the seat; the reserved services sell out on weekends. Some services are non-reserved and first come first served.'),
    item('c13c', '10:00', 'activity', 'Shirakawa-go: Shiroyama viewpoint, Wada House, the walk between the farmhouses', location='Ogimachi village', endTime='15:00', cost=1000, currency='JPY', notes='Viewpoint shuttle or a 20 min walk up. Wada House (¥400) is the big one you can go inside. The open-air museum across the river is quieter. Snow boots and crampons: the paths are icy.'),
    item('c13d', '12:30', 'food', 'Lunch: soba or Hida beef croquette from a stand', location='Village', cost=1300, currency='JPY'),
    item('c13e', '15:00', 'stay', 'Check in at a gassho-zukuri farmhouse minshuku', location='See Stays; book via the Shirakawa-go Tourist Association site', notes='Day-trippers leave on the last buses around 5; then the village is yours. Dinner is around the irori hearth with the family.'),
    item('c13f', '17:00', 'activity', 'Blue hour in the empty village; Shirakawa-go no Yu onsen (optional)', location='Village', cost=700, currency='JPY'),
    item('c13g', '18:00', 'food', 'Irori hearth dinner at the farmhouse', location='Your minshuku', cost=0, currency='JPY', notes='Grilled river fish, mountain vegetables, local tofu, included in the price. Bring a small gift or just good manners.'),
  ],
  '2027-02-14': [
    item('c14a', '07:00', 'activity', 'Dawn walk before the buses arrive', location='Village', endTime='08:00', cost=0, currency='JPY'),
    item('c14b', '09:50', 'bus', 'Nohi bus Shirakawa-go → Takayama', location='Shirakawa-go bus terminal', endTime='10:40', cost=1800, currency='JPY'),
    item('c14c', '11:00', 'activity', 'Takayama Jinya (Edo government house) or Hida Folk Village', location='Takayama', endTime='13:00', cost=700, currency='JPY', notes='Jinya is the only surviving Edo-period provincial government office; the Folk Village is a hillside of relocated farmhouses if you want more of yesterday.'),
    item('c14d', '13:00', 'food', 'Takayama ramen', location='An old shop in the centre', cost=1000, currency='JPY', notes='Thin curly noodles in a soy-shoyu broth; the town’s everyday lunch.'),
    item('c14e', '14:40', 'bus', 'Express bus Takayama → Matsumoto over the Northern Alps (via Hirayu Onsen)', location='Takayama Nohi Bus Center', endTime='17:15', cost=3800, currency='JPY', notes='Winter timetable, about 2h30, seat reservations mandatory (Alpico/Nohi, opens a month ahead). Sit on the left for the Alps.'),
    item('c14f', '17:30', 'stay', 'Check in, Matsumoto (2 nights); collect the suitcase', location='See Stays'),
    item('c14g', '19:00', 'food', 'Dinner on Nakamachi: Shinshu soba, sansai (mountain vegetables), basashi if you dare', location='Nakamachi street', cost=3000, currency='JPY'),
  ],
  '2027-02-15': [
    item('c15a', '08:30', 'activity', 'Matsumoto Castle at opening', location='10 min walk from the station', endTime='10:00', cost=700, currency='JPY', notes='1590s original black keep, steep ladders inside, Alps behind it. Go at 8:30 and you climb it alone.'),
    item('c15b', '10:00', 'activity', 'Nakamachi kura street and Nawate street', location='Old town', endTime='11:00', cost=0, currency='JPY', notes='Whitewashed storehouses, frog-themed shopping street by the river.'),
    item('c15c', '11:10', 'train', 'Local trains Matsumoto → Shiojiri → Narai', location='Matsumoto Station', endTime='12:20', cost=770, currency='JPY', notes='Change at Shiojiri; about an hour with the change. Roughly hourly, so check the timetable the night before.'),
    item('c15d', '12:30', 'activity', 'Narai-juku, Edo post town on the Nakasendo', location='1 km street from the station', endTime='15:00', cost=0, currency='JPY', notes='Lacquerware workshops, sake shop, temples up the side lanes, snow on the eaves. A working village, not a theme park.'),
    item('c15e', '13:00', 'food', 'Gohei-mochi and Kiso soba', location='Any shop with a menu outside', cost=1500, currency='JPY'),
    item('c15f', '15:20', 'train', 'Local trains Narai → Matsumoto', location='Narai Station', endTime='16:30', cost=770, currency='JPY'),
    item('c15g', '17:00', 'activity', 'Asama Onsen public bath (optional)', location='Bus 20 min from Matsumoto Station', cost=700, currency='JPY', status='idea', notes='Hot Plaza Asama; the local onsen rather than a resort one.'),
    item('c15h', '19:00', 'food', 'Sanzoku-yaki (Matsumoto’s giant fried chicken) or a soba dinner', location='Around the station', cost=2000, currency='JPY'),
  ],
  '2027-02-16': [
    item('c16a', '09:00', 'activity', 'Coffee, and the Matsumoto City Museum of Art if you like Yayoi Kusama (she is from here)', location='Matsumoto', endTime='10:15', cost=410, currency='JPY', status='idea'),
    item('c16b', '10:40', 'train', 'Limited Express Azusa Matsumoto → Shinjuku', location='Matsumoto Station', endTime='13:10', cost=6620, currency='JPY', notes='~2h30, all seats reserved.'),
    item('c16c', '13:35', 'train', 'Narita Express Shinjuku → Narita T2', location='Shinjuku, N’EX platforms', endTime='15:00', cost=0, currency='JPY', notes='~80 min. Covered by the N’EX round-trip ticket bought on day 1 (it is valid from Shinjuku too).'),
  ],
}
for d in days:
    if d['date'] in B_DAYS:
        d['variants'] = {'culture': B_DAYS[d['date']]}
        for it in B_ITEMS.get(d['date'], []):
            it['variant'] = 'culture'; d['items'].append(it)

for st in stays:
    if st['town'] in ('Nozawa Onsen', 'Togari Onsen (fallback)', 'Myoko Kogen (alternative base)'):
        st['variant'] = 'ski'
stays += [
  dict(id='s-b1', name='Koyasan shukubo: Ekoin, Fukuchiin or Shojoshin-in', town='Koyasan', type='Temple lodging, tatami room, 2 meals', status='planned', variant='culture', pricePerNightAud=175, nights=1, priceNote='¥15,000-22,000 pp with meals est.', checkIn='2027-02-11', checkOut='2027-02-12', distance='Central Koyasan, walk to Okunoin', url='https://koyasan-shukubo.net/en/', notes='Book on the official Shukubo Association site (English). Ekoin is the most foreigner-friendly and runs the night tour; Fukuchiin has an onsen; Shojoshin-in sits right at the Okunoin entrance. Solo is normal.'),
  dict(id='s-b2', name='Takayama: Tabino Hotel Hida Takayama or Country Hotel Takayama', town='Takayama', type='Business hotel with a big bath', status='planned', variant='culture', pricePerNightAud=130, nights=1, priceNote='est.; verify', checkIn='2027-02-12', checkOut='2027-02-13', distance='Next to the station and the Nohi bus centre', url='https://travel.rakuten.com/', notes='Being at the station matters here: two bus departures in two days.'),
  dict(id='s-b3', name='Shirakawa-go gassho-zukuri farmhouse minshuku', town='Shirakawa-go', type='Thatched farmhouse, irori dinner and breakfast', status='planned', variant='culture', pricePerNightAud=190, nights=1, priceNote='¥15,000-25,000 pp with 2 meals', checkIn='2027-02-13', checkOut='2027-02-14', distance='In the village', url='https://www.travelclassroom.net/eng/shirakawa-stay.html', notes='Book through the Shirakawa-go Tourist Association reservation system (that guide explains it step by step). Around 40 places; ask for single occupancy. Not every house takes solo guests, so start early. No light-up event in Feb 2027, so no lottery.'),
  dict(id='s-b4', name='Matsumoto: Hotel Buena Vista or a Dormy Inn', town='Matsumoto', type='City hotel or business hotel with bath', status='planned', variant='culture', pricePerNightAud=110, nights=2, priceNote='est.; verify', checkIn='2027-02-14', checkOut='2027-02-16', distance='Walk to the station and the castle', url='https://travel.rakuten.com/', notes='Send the suitcase here from Osaka. Tell them a parcel arrives on the 13th for a guest checking in on the 14th.'),
]

for f in food:
    if f['town'] in ('Nozawa Onsen', 'Nagano'):
        f['variant'] = 'ski'
food += [
  dict(id='fb1', town='Koyasan', dish='Shojin ryori and goma-dofu', where='Your temple, dinner and breakfast', why='Buddhist vegetarian cooking at its source. The sesame tofu is Koyasan’s own; buy a block from Hamadaya to take on the train.', priceBand='¥¥', variant='culture'),
  dict(id='fb2', town='Takayama', dish='Hida beef with hoba-miso', where='A small grill off Sanmachi', why='Local beef cooked on a magnolia leaf over miso. The regional dish, not a tourist invention.', priceBand='¥¥¥', variant='culture'),
  dict(id='fb3', town='Takayama', dish='Takayama ramen', where='An old shop in the centre', why='Soy broth, thin curly noodles, what locals eat for lunch.', priceBand='¥', variant='culture'),
  dict(id='fb4', town='Takayama', dish='Mitarashi dango at the morning market', where='Miyagawa market stalls', why='Soy-glazed, savoury not sweet here. Breakfast while you browse.', priceBand='¥', variant='culture'),
  dict(id='fb5', town='Shirakawa-go', dish='Irori hearth dinner', where='Your farmhouse', why='Char-grilled river fish, mountain vegetables, tofu, cooked over the sunken hearth. This is why you stay the night.', priceBand='¥¥', variant='culture'),
  dict(id='fb6', town='Matsumoto', dish='Shinshu soba and sansai', where='Nakamachi street shops', why='Nagano’s buckwheat noodles with foraged mountain vegetables; Matsumoto is the soba capital.', priceBand='¥', variant='culture'),
  dict(id='fb7', town='Matsumoto', dish='Sanzoku-yaki', where='Izakaya near the station', why='A whole marinated chicken thigh, deep fried. Matsumoto’s comfort food.', priceBand='¥', variant='culture'),
]

for c in checklist:
    if c['id'] in ('ck3', 'ck15', 'ck16', 'ck21', 'ck25', 'ck26', 'ck28'):
        c['variant'] = 'ski'
checklist += [
  dict(id='ckb1', group='Points and bookings', text='Plan B: book the Koyasan temple night on the Shukubo Association site (koyasan-shukubo.net), 11 Feb, 1 person with dinner and breakfast', due='2026-10-15', variant='culture'),
  dict(id='ckb2', group='Points and bookings', text='Plan B: book a Shirakawa-go gassho farmhouse for 13 Feb through the Tourist Association reservation system (solo)', due='2026-10-31', variant='culture', notes='The TravelClassroom guide walks through the form. Not all houses take single guests; try several.'),
  dict(id='ckb3', group='Points and bookings', text='Plan B: book Takayama (12 Feb) and Matsumoto (14-16 Feb) hotels', due='2026-11-30', variant='culture'),
  dict(id='ckb4', group='Points and bookings', text='Plan B: reserve the Nohi buses Takayama ↔ Shirakawa-go (13 and 14 Feb) and the Takayama → Matsumoto winter express (14 Feb, reservation mandatory)', due='2027-01-14', variant='culture', notes='Both open about a month ahead on nouhibus.co.jp and the Alpico site.'),
  dict(id='ckb5', group='Points and bookings', text='Plan B: reserve the Nankai Limited Express Koya (11 Feb), Hida express Nagoya → Takayama (12 Feb) and Azusa Matsumoto → Shinjuku (16 Feb)', due='2027-01-16', variant='culture'),
  dict(id='ckb6', group='In Japan', text='Plan B: buy the Koyasan World Heritage Ticket at Nankai Namba on the morning of 11 Feb', due='2027-02-11', variant='culture'),
]

for pl in places:
    if pl['id'] in ('p13', 'p14', 'p15', 'p16', 'p17', 'p18', 'p22', 'p23', 'p24'):
        pl['variant'] = 'ski'
places += [
  dict(id='pb1', name='Koyasan: Okunoin cemetery and mausoleum', kind='other', town='Koyasan', lat=34.2160, lng=135.6060, variant='culture'),
  dict(id='pb2', name='Koyasan: Danjo Garan and Kongobuji', kind='other', town='Koyasan', lat=34.2130, lng=135.5810, variant='culture'),
  dict(id='pb3', name='Takayama Sanmachi old town', kind='town', town='Takayama', lat=36.1420, lng=137.2590, variant='culture'),
  dict(id='pb4', name='Shirakawa-go (Ogimachi village)', kind='town', town='Shirakawa-go', lat=36.2570, lng=136.9060, variant='culture'),
  dict(id='pb5', name='Matsumoto Castle', kind='other', town='Matsumoto', lat=36.2384, lng=137.9690, variant='culture'),
]

questions.insert(0, dict(id='q12', question='Plan A (ski) or Plan B (no skiing)?', why='Both use the flights already booked and the same Osaka and USJ days; they split on Thursday 11 Feb. Plan A: Nozawa Onsen for five nights, three ski days plus a rural Sunday, hinges on finding a solo room in a sold-out week. Plan B: a temple night at Koyasan, Takayama, a farmhouse night in Shirakawa-go, Matsumoto castle and the Narai post town: more moving about, four different beds, no dependence on Nozawa, and about A$400-500 cheaper because there are no lifts or rental. Lost workdays are identical. The plan switch at the top of the menu flips every page between them.', options=['Plan A: ski trip (Nozawa Onsen)', 'Plan B: countryside and culture (Koyasan, Takayama, Shirakawa-go, Matsumoto, Narai)', 'Hybrid: Plan B but swap Matsumoto’s two nights for two nights in Nozawa without skiing (onsen village, snow, food)'], recommendation='Decide by accommodation: if a Nozawa room lands by late October, Plan A. If not, Plan B is not a consolation prize; the Koyasan and Shirakawa-go nights are two of the best things you can do in Japan in winter, and every bed in it is easier to get.', answer='', resolved=False))

trip = dict(
  meta=dict(title='Japan 2027', start='2027-02-08', end='2027-02-17', homeCurrency='AUD', jpyPerAud=RATE, updatedAt=UPDATED, version=1,
            about='Solo ski trip. Confirmed: JQ815 BNE→SYD and the Business Classic Reward SYD→MEL→NRT on 8 Feb. Home Tue 16 Feb on QF80 + QF1256 (booked). Everything else is planned from research done 13 Sep 2026; prices marked est. need checking when booking.'),
  days=days,
  flights=dict(
    confirmed=[{('from' if k == 'from_' else k): v for k, v in f.items()} for f in flights['confirmed']],
    legs=flights['legs'],
    lounges=flights['lounges'],
  ),
  variants=dict(active='ski', list=[dict(id='ski', name='Plan A: Ski trip (Nozawa)', short='A: Ski'), dict(id='culture', name='Plan B: No skiing, countryside and culture', short='B: Culture')]),
  foodGuide=FOOD_GUIDE, staysGuide=STAYS_GUIDE, points=points, stays=stays, food=food, budget=budget, checklist=checklist, places=places, questions=questions,
)
with open('data/trip.json', 'w') as f:
    json.dump(trip, f, ensure_ascii=False, indent=2); f.write('\n')
print('wrote data/trip.json', sum(len(d['items']) for d in days), 'items,', len(stays), 'stays,', len(food), 'food,', len(checklist), 'todos,', len(questions), 'questions')
