#!/usr/bin/env python3
"""Builds data/trip.json from the research. Re-run after editing; the app reads the JSON directly."""
import json, datetime

UPDATED = datetime.datetime.now(datetime.timezone.utc).replace(microsecond=0).isoformat().replace('+00:00', 'Z')
RATE = 108  # JPY per AUD used for planning (mid-market ~110 in Sep 2026; 108 leaves room for card spreads)

def item(id, time, type, title, **kw):
    d = dict(id=id, time=time, type=type, title=title, status=kw.pop('status', 'planned'))
    d.update({k: v for k, v in kw.items() if v is not None})
    return d

days = [
  dict(id='d0208', date='2027-02-08', title='Fly out via Sydney and Melbourne', base='Overnight flight', notes='Times on this day are shown in local time at each airport. Sydney and Melbourne are one hour ahead of Queensland in February (daylight saving).', items=[
    item('a1', '08:00', 'transfer', 'Drive Gympie → Brisbane Airport', location='Bruce Hwy, ~167 km, about 1h45', notes='Book AIRPARK online beforehand (free shuttle every 10-15 min to the domestic terminal). Leaving at 8 puts you at the terminal by ~10:15, an hour and a bit before an 11:30 flight even with Bruce Highway delays.', cost=None),
    item('a2', '11:30', 'flight', 'Qantas Brisbane → Sydney (to be booked)', location='BNE domestic → SYD T3', endTime='14:05', notes='Departs 11:30 Queensland time, lands about 2:05pm Sydney time (Sydney is an hour ahead in February). Book on a QF flight number so bags through-check to Narita and you land at T3, the same terminal as QF481. Aim to land by 3pm Sydney time at the latest. Tip: check in online for QF481 the day before; its Business boarding pass gets you into the T3 Business Lounge the moment you land. Cost lives in Flights & points.', status='idea'),
    item('a3', '14:00', 'activity', 'Qantas Domestic Business Lounge, Sydney T3', location='Opposite gates 4-5, up the escalator, left door', notes='Your Business ticket gets you in. Bags should already be checked through, so you stay airside. Shower, eat, charge everything.'),
    item('a4', '18:30', 'flight', 'QF481 Sydney → Melbourne', location='SYD T3 → MEL T1', endTime='20:05', status='booked', notes='Business, A321neo, 1h35. Confirmed.'),
    item('a5', '20:15', 'transfer', 'Melbourne T1 → T2 walk, then immigration', location='Covered walkway, one level up, 3-5 min', notes='Bags transfer automatically on the one booking. Allow 30-40 min for security and outbound immigration.'),
    item('a6', '21:00', 'activity', 'Qantas International First Lounge, Melbourne T2 (Titanium pass)', location='Airside, level 3, escalator near gates 9-10', notes='Use one of your two Titanium First Lounge invitations here (show it in the Qantas app). Proper restaurant dining, so skip the Sydney lounge food and eat here. Be at the gate by ~10:45pm. Fallback if anything goes wrong with the pass: the International Business Lounge on level 1 is covered by the ticket.'),
    item('a7', '23:30', 'flight', 'QF49 Melbourne → Tokyo Narita', location='MEL T2 → NRT T2', endTime='07:50', status='booked', notes='Business, A330-200, 10h20, lands 7:50am Tuesday. Sleep as much as you can: Japan is only 1 hour behind Queensland, so jet lag is minimal.'),
  ]),
  dict(id='d0209', date='2027-02-09', title='Land, straight down to Osaka', base='Osaka', notes='Long travel day on purpose: it puts you in Osaka the night before the calmest weekday to do Universal Studios.', items=[
    item('b1', '07:50', 'note', 'Land Narita T2, immigration and customs', location='Narita T2', notes='Have the Visit Japan Web QR code ready (immigration + customs in one). Budget about an hour. Pick up your bag, switch on the eSIM, and withdraw ¥30,000-40,000 at the 7-Eleven ATM in the terminal (Nozawa is largely cash-only and has one foreign-card ATM, at the post office). Suica: Welcome Suica Mobile in Apple Wallet if you have an iPhone; on Android buy a physical Welcome Suica at the JR counter.'),
    item('b2', '09:45', 'train', 'Narita Express → Tokyo Station', location='NRT T2 station, B1', endTime='10:45', cost=3070, currency='JPY', notes='~55 min. Buy at the JR East ticket office or machine (the N’EX round-trip ticket for foreign passports, ¥5,200, is worth it because you come back this way on the 15th).'),
    item('b3', '11:00', 'food', 'Ekiben (station bento) from Ekibenya Matsuri', location='Tokyo Station, central passage', cost=1500, currency='JPY', notes='The most Japanese lunch there is. Grab one for the Shinkansen. Not a trendy place, just a shop with 200 regional bento.'),
    item('b4', '11:30', 'train', 'Nozomi Shinkansen Tokyo → Shin-Osaka', location='Tokyo Station, platforms 14-19', endTime='14:00', cost=14720, currency='JPY', notes='~2h30, every 10 min. Reserve a seat (opens one month ahead on smart-EX). A normal suitcase under 160 cm total is fine; only bags over 160 cm need the oversized-baggage seat.'),
    item('b5', '14:15', 'transfer', 'Shin-Osaka → hotel', location='JR local to Osaka / Fukushima, or Yumesaki line to Universal City', endTime='15:00', cost=300, currency='JPY'),
    item('b6', '15:00', 'stay', 'Check in, Osaka (2 nights)', location='See Stays for the shortlist', notes='Solo, private room. Business hotels around Fukushima or Tenma are quiet, cheap and 15-25 min from USJ by train.'),
    item('b6b', '15:20', 'transfer', 'Send the suitcase ahead to Nozawa by Yamato courier (takkyubin)', location='Hotel front desk', cost=3000, currency='JPY', notes='Ask the desk for “takkyubin to this address” (show the Nozawa lodging’s name and address in Japanese, kept in Notes). Two days is the standard lead time, so sending Tuesday means it is waiting Thursday. Keep a daypack with two days of clothes, USJ tickets and Friday’s ski base layers. Confirm beforehand that the lodging accepts parcels (most do).'),
    item('b7', '17:00', 'activity', 'Walk Nakazakicho and Tenma', location='Nakazakicho (old wooden lanes) → Tenjinbashisuji shopping arcade → Tenma', notes='Low-key neighbourhoods a short train ride from Umeda. Tenjinbashisuji is 2.6 km of covered arcade where locals shop.'),
    item('b8', '18:30', 'food', 'Dinner in the Tenma izakaya alleys', location='Around Tenma station, under the tracks', cost=3500, currency='JPY', notes='Standing bars and tiny izakaya, mostly Japanese customers. Order doteyaki (beef tendon simmered in miso) and kushikatsu. Early night; tomorrow starts at 7.'),
  ]),
  dict(id='d0210', date='2027-02-10', title='Universal Studios Japan and Super Nintendo World', base='Osaka', notes='Wednesday is the calmest weekday in the window (Thursday is a public holiday, and the weekend follows). Buy the Studio Pass and an Express Pass that includes Super Nintendo World entry as soon as they go on sale for this date.', items=[
    item('c1', '07:00', 'train', 'Train to Universal City', location='Osaka Station platform 1 → Universal City (JR Yumesaki line, ~12 min direct)', cost=200, currency='JPY'),
    item('c2', '07:45', 'note', 'Be at the gates before official opening', location='USJ main entrance', notes='Posted opening is usually 9:00-9:30 in February but the park regularly opens 30-60 min early. Being there by 7:45 matters if you are relying on the free timed-entry ticket. Log into the USJ app the night before and make sure the eSIM has data: the timed-entry ticket is app-only (since Jan 2026) and needs signal at the gate.'),
    item('c3', '08:30', 'activity', 'Enter USJ; claim Super Nintendo World timed entry in the app the second you are through the gate', location='USJ', cost=10900, currency='JPY', notes='1-Day Studio Pass, date-priced (¥8,900 low season up to ¥11,800 peak in 2026; Feb 2027 not published yet). If you bought an Express Pass with area entry you already have a slot and can skip the scramble.'),
    item('c4', '09:30', 'activity', 'Super Nintendo World: Mario Kart, Yoshi’s Adventure, Donkey Kong Country', location='Super Nintendo World', cost=4800, currency='JPY', notes='The ¥4,800 is the Power-Up Band (optional but it is the whole point of the key challenges and Bowser Jr boss fight). Ride Mario Kart first, then Donkey Kong’s Mine Cart, then wander.'),
    item('c5', '12:30', 'food', 'Kinopio’s Cafe (Toad’s cafe)', location='Super Nintendo World', cost=2500, currency='JPY', notes='Reserve in the app on the day if slots show. Otherwise Yoshi’s Snack Island for a quick bite.'),
    item('c6', '14:00', 'activity', 'Rest of the park: Jurassic Park, Harry Potter area, Jaws', location='USJ', endTime='19:00', notes='Single Rider lines are the solo traveller’s cheat code and are free. February weekdays historically close around 7pm, so the day is shorter than summer: front-load Nintendo World.'),
    item('c7', '19:45', 'food', 'Okonomiyaki dinner back in town', location='A neighbourhood okonomiyaki counter near the hotel (see Food)', cost=1800, currency='JPY'),
  ]),
  dict(id='d0211', date='2027-02-11', title='Osaka → Narai-juku (Edo post town) → Nozawa Onsen', base='Nozawa Onsen', notes='National Foundation Day, so reserve every seat a month ahead. The Shinano express runs straight through the Kiso valley, so this is the day to see rural Japan for free: hop off at Kiso-Fukushima, ride one local stop to Narai-juku, walk the 1 km Edo-period street in the snow, then carry on to Nagano. Travel hands-free: the suitcase goes ahead by courier from Osaka (see Tuesday).', items=[
    item('e1', '08:00', 'transfer', 'Check out (daypack only), to Shin-Osaka', location='Shin-Osaka', cost=300, currency='JPY'),
    item('e2', '08:40', 'train', 'Nozomi Shin-Osaka → Nagoya', location='Shin-Osaka', endTime='09:30', cost=6880, currency='JPY', notes='~50 min, reserved seat.'),
    item('e3', '10:00', 'train', 'Limited Express Shinano Nagoya → Kiso-Fukushima', location='Nagoya, Chuo line platforms', endTime='11:25', cost=6000, currency='JPY', notes='Reserved seat on the holiday. Sit on the left for the Kiso river. Buy the ticket through to Nagano with a break at Kiso-Fukushima, or two tickets; either is fine.'),
    item('e4', '11:45', 'train', 'Local train Kiso-Fukushima → Narai', location='Kiso-Fukushima, Chuo line local (about every hour)', endTime='12:05', cost=330, currency='JPY', notes='20 minutes. Check the local timetable when you reserve the Shinano so the connection is short.'),
    item('e5', '12:10', 'activity', 'Narai-juku: the best-preserved post town on the old Nakasendo road', location='Narai station → 1 km of Edo-period wooden inns and shops', endTime='14:30', cost=0, currency='JPY', notes='A working village, not a theme park: lacquerware workshops, a sake shop, temples up the side lanes, snow on the eaves. Narai station has no lockers but a ¥300 bag-minding desk (8:30-16:00) if you are carrying anything. Lunch here: soba or gohei-mochi (grilled rice cake with walnut-miso), the Kiso valley specialty. The Kiso Ohashi bridge and Kamidonya museum are worth 20 minutes.'),
    item('e6', '13:00', 'food', 'Gohei-mochi and Kiso soba in Narai', location='Any shop on the main street with a menu outside', cost=1500, currency='JPY'),
    item('e7', '14:40', 'train', 'Local train Narai → Shiojiri, then Shinano Shiojiri → Nagano', location='Narai station', endTime='16:35', cost=4500, currency='JPY', notes='Local 25 min to Shiojiri, change to the Shinano (about hourly) for ~65 min to Nagano. Reserve the Shiojiri → Nagano seat too.'),
    item('e8', '17:00', 'train', 'Hokuriku Shinkansen Nagano → Iiyama', location='Nagano Station', endTime='17:12', cost=1500, currency='JPY', notes='12 minutes. The Nozawa Onsen Liner leaves about 10 min after each Shinkansen.'),
    item('e9', '17:25', 'bus', 'Nozawa Onsen Liner → Nozawa Onsen', location='Iiyama Station, bus stop out the front', endTime='17:50', cost=600, currency='JPY', notes='25 min. Taxi is the fallback (¥6,000-7,000). Tell the lodging you arrive about 6pm so dinner is held.'),
    item('e10', '18:00', 'stay', 'Check in, Nozawa Onsen (4 nights)', location='See Stays', notes='Your suitcase should be waiting (sent by courier on Tuesday). If it is not, the daypack has tomorrow’s ski layers.'),
    item('e11', '18:30', 'food', 'Ryokan dinner (or Wakagiri if no meals booked)', location='Lodging / main street', cost=3000, currency='JPY', notes='Ryokan dinners are served at a fixed time; say so at check-in. If you are eating out, Wakagiri is the local favourite for a home-style set meal.'),
    item('e12', '20:00', 'activity', 'Oyu, the main public bathhouse', location='Centre of the village', cost=0, currency='JPY', notes='13 free soto-yu bathhouses run by the village. Wash first, no towel in the water, keep it quiet, no photos. Bring a small towel; expect it hot.'),
  ]),
  dict(id='d0212', date='2027-02-12', title='Ski Nozawa, day 1', base='Nozawa Onsen', notes='Thursday was a stand-alone public holiday, so Friday is the comparatively quiet day before the weekend crowd arrives. Be on the Nagasaka gondola at opening (8:30) and head to Yamabiko at the top.', items=[
    item('f0', '07:45', 'activity', 'Ski rental fitting (pre-booked, 4 days)', location='Village rental shop', cost=17800, currency='JPY', notes='4 days x ¥4,450 standard set (skis, boots, poles) at a village shop; the resort shop is ¥5,500/day. Book online in January with your boot size in cm: big sizes (29 cm+) run out in peak weeks. Ski wear can be rented too.'),
    item('f1', '08:15', 'ski', 'Nozawa Onsen Snow Resort, full day', location='Nagasaka gondola', endTime='16:00', cost=8000, currency='JPY', notes='Special Pack: 1-day lift pass + ¥1,000 lunch voucher (2025-26 price; expect +5-10%). 297 ha, 1,085 m vertical, 10 km longest run (Skyline). Yamabiko for tree runs, Uenotaira for cruising.'),
    item('f2', '12:30', 'food', 'Lunch on the mountain with the voucher', location='Yamabiko or Uenotaira restaurants', cost=500, currency='JPY', notes='Curry rice or ramen; the voucher covers most of it.'),
    item('f3', '16:30', 'activity', 'Onsen: try a different soto-yu (Kuma no Tearai or Shinyu)', location='Village', cost=0, currency='JPY'),
    item('f4', '18:30', 'food', 'Soba at Sobadokoro Daimon', location='Main street, 100-year-old family shop', cost=1800, currency='JPY', notes='Hand-cut Shinshu soba. Order it zaru (cold) even in winter; it is how locals judge a soba shop.'),
  ]),
  dict(id='d0213', date='2027-02-13', title='Ski Nozawa, day 2', base='Nozawa Onsen', notes='Saturday of the long weekend: busy, so early start. Karasawa and Paradise are quieter than the gondola-top runs. Night skiing on Hikage runs on selected nights; check the board. Rental gear is easiest to fit first thing Friday, so plan on being at the shop when it opens.', items=[
    item('g1', '08:15', 'ski', 'Nozawa Onsen Snow Resort, full day', location='Hikage gondola', endTime='16:00', cost=8000, currency='JPY', notes='Special Pack again. Explore Karasawa and Paradise; the Skyline run top to bottom late afternoon when it empties.'),
    item('g2', '12:30', 'food', 'Mountain lunch', location='On mountain', cost=500, currency='JPY'),
    item('g3', '17:00', 'activity', 'Onsen eggs at the Ogama', location='Ogama (the village’s boiling cooking spring, locals only in the water but you can watch and buy eggs nearby)', cost=300, currency='JPY'),
    item('g4', '18:30', 'food', 'Izakaya dinner: basashi (horse sashimi) and nozawana', location='A village izakaya (see Food)', cost=3500, currency='JPY'),
  ]),
  dict(id='d0214', date='2027-02-14', title='Rural day: Togakushi shrine in the snow, then Zenko-ji', base='Nozawa Onsen', notes='Sunday is the most crowded ski day of the trip (long-weekend Tokyo crowd), so it is the cheapest day to give up. Togakushi is a mountain shrine village above Nagano: a 2 km avenue of 400-year-old cedars leading to the inner shrine, all under deep snow in February, plus the soba the village is famous for. Back via Zenko-ji, one of Japan’s great temples. If it is dumping powder on Sunday morning, swap this for skiing and call the day a rest instead; the ski item below is kept as the alternative.', items=[
    item('h1', '08:05', 'bus', 'Nozawa Onsen Liner → Iiyama, Shinkansen → Nagano', location='Village bus stop → Iiyama → Nagano', endTime='09:05', cost=2100, currency='JPY', notes='Check the Liner and Shinkansen times the night before; Sunday services are the same as weekdays.'),
    item('h2', '09:30', 'bus', 'Alpico bus 70 Nagano Station → Togakushi', location='Nagano Station east side, bus stop 7', endTime='10:35', cost=1450, currency='JPY', notes='About 60 min to Chusha (middle shrine). In winter a separate winter service stops at the Okusha entrance; if the bus you are on does not, get off at Chusha and walk up the road ~30 min or take a taxi. The Zenko-ji & Togakushi 1-day bus ticket (Alpico) covers the whole day’s buses and is cheaper than singles.'),
    item('h3', '10:40', 'activity', 'Okusha cedar avenue and inner shrine', location='Okusha entrance → Zuishinmon gate → Okusha', endTime='13:00', cost=0, currency='JPY', notes='20 min flat walk through the cedars to the red Zuishinmon gate, then a steeper 20-30 min to the inner shrine, all on packed snow. Bring or buy simple crampons (Workman or Don Quijote sell them for ~¥1,500) and waterproof boots; ski gloves and shell are perfect. Quiet, no ropes, no gates: this is the rural Japan you asked for.'),
    item('h4', '13:15', 'food', 'Togakushi soba at Chusha', location='Around Chusha (middle shrine): Uzuraya is the famous one, several quieter shops nearby', cost=1600, currency='JPY', notes='Togakushi soba is served in small “bocchi” bundles on a bamboo tray. Order zaru, add the local wasabi. Cash.'),
    item('h5', '14:10', 'activity', 'Chusha shrine and the ninja museum village (optional)', location='Chusha', endTime='15:00', cost=0, currency='JPY', notes='Chusha has an 800-year-old triple cedar at its gate. Skip the ninja stuff unless it amuses you.'),
    item('h6', '15:10', 'bus', 'Bus 70 Togakushi → Zenko-ji (Daimon stop)', location='Chusha bus stop', endTime='16:05', cost=1300, currency='JPY', notes='Get off at Zenkoji Daimon, not the station. Last buses back down are around 17:00-18:00; check the winter timetable.'),
    item('h7', '16:10', 'activity', 'Zenko-ji temple at dusk', location='Zenko-ji, Nagano', endTime='17:00', cost=600, currency='JPY', notes='1,400-year-old temple, the reason Nagano exists. Walk the main hall, do the pitch-black “kaidan meguri” tunnel under the altar to touch the key to paradise (¥600). The approach street (Nakamise) has oyaki and miso shops.'),
    item('h8', '17:15', 'train', 'Nagano → Iiyama → Nozawa Onsen', location='Nagano Station (15 min walk or bus from Zenko-ji)', endTime='18:40', cost=2100, currency='JPY'),
    item('h9', '19:00', 'food', 'Last Nozawa dinner: oyaki, nozawana and a nabe hotpot', location='Village', cost=3000, currency='JPY'),
    item('h10', '20:30', 'note', 'Pack; return rental gear tonight if the shop allows, or first thing tomorrow', location='Lodging'),
    item('h11', '08:15', 'ski', 'ALTERNATIVE if it is a powder day: ski Nozawa instead', location='Nagasaka gondola', endTime='16:00', cost=8000, currency='JPY', status='skip', notes='Marked as skipped so it stays out of the budget. Flip the status to Planned and set the Togakushi items to Skipped if you choose to ski. Sunday lift lines ease after 2pm.'),
  ]),
  dict(id='d0215', date='2027-02-15', title='Quiet Monday morning ski, then home via Tokyo', base='Overnight flight', notes='Monday morning is the emptiest the mountain will be all trip. Two hours of skiing, then a comfortable run to Narita for a 9:45pm departure.', items=[
    item('i1', '08:30', 'ski', 'Short morning ski (optional)', location='Nagasaka gondola', endTime='10:45', cost=6000, currency='JPY', status='idea', notes='Only if the lodging lets you check out late and the rental shop opens early. A half-day/morning pass if offered, else skip and have a slow breakfast and one last onsen.'),
    item('i2', '11:30', 'bus', 'Nozawa Onsen Liner → Iiyama Station', location='Village bus stop', endTime='11:55', cost=600, currency='JPY'),
    item('i3', '12:15', 'train', 'Hokuriku Shinkansen Iiyama → Tokyo', location='Iiyama Station', endTime='14:10', cost=8500, currency='JPY', notes='~1h50.'),
    item('i4', '14:30', 'train', 'Narita Express Tokyo → Narita T2', location='Tokyo Station', endTime='15:30', cost=0, currency='JPY', notes='Covered by the N’EX round trip ticket bought on day 1.'),
    item('i5', '16:00', 'note', 'Narita T2: check in (Qantas counters), drop bag', location='NRT T2', notes='Check-in closes 60 min before departure. Plenty of buffer.'),
    item('i6', '18:00', 'food', 'Dinner at Narita T2 food court', location='NRT T2, 4F', cost=1500, currency='JPY', notes='Tonkatsu or ramen; last Japanese meal.'),
    item('i7', '21:45', 'flight', 'QF62 Narita → Brisbane (to be booked)', location='NRT T2 → BNE international', endTime='07:45', status='idea', notes='A330-300, ~9 h, lands 7:45am Tuesday. Two-class aircraft: there is no Premium Economy on this route. See Flights & points for the options.'),
  ]),
  dict(id='d0216', date='2027-02-16', title='Land Brisbane, drive home', base='Home', notes='', items=[
    item('j1', '07:45', 'note', 'Land Brisbane, immigration, bag', location='BNE international'),
    item('j2', '09:00', 'transfer', 'AIRPARK shuttle to the car, coffee, drive to Gympie', location='BNE → Gympie, ~1h45', notes='Do not drive tired. Get a proper coffee and breakfast at the airport first; the Bruce Highway is not the place to nod off.'),
  ]),
]

flights = dict(
  confirmed=[
    dict(id='qf481', flight='QF481', from_='Sydney T3', to='Melbourne T1', date='2027-02-08', arrDate='2027-02-08', dep='18:30', arr='20:05', cabin='Business', aircraft='A321neo', duration='1h35', notes='Business Classic Reward. Domestic leg; check-in at Sydney T3. Same booking as QF49, so the connection is protected.'),
    dict(id='qf49', flight='QF49', from_='Melbourne T2', to='Tokyo Narita T2', date='2027-02-08', arrDate='2027-02-09', dep='23:30', arr='07:50', cabin='Business', aircraft='A330-200', duration='10h20', notes='Business Classic Reward. Seasonal Monday service (runs Sun/Mon/Wed/Fri, 2 Dec 2026 to late Mar 2027). Taxes paid: A$450.', cashAud=450),
  ],
  legs=[
    dict(id='leg-feeder', name='Home to Sydney, Mon 8 Feb', chosenOptionId='opt-qf-bne', notes='This is a separate ticket from the Business reward, so it is not protected if it runs late. Pick a Qantas (QF) flight so bags check through and you arrive at T3, and land by 3pm Sydney time. Brisbane has ~18 Qantas departures a day as fallback; Sunshine Coast has 3.', options=[
      dict(id='opt-qf-bne', rank=1, label='Qantas Brisbane → Sydney, late morning', route='BNE → SYD T3', date='2027-02-08', dep='11:30', arr='14:05', duration='1h35', cashAud=140, priceNote='A$95-365 range; est. mid', points=9200, pointsTaxAud=58, status='planned', notes='Recommended. Park at BNE AIRPARK (A$109 for 8 days). With QF62 landing at BNE on the way home, this is the cheapest and simplest overall. 11:30 Queensland time → ~2:05pm Sydney time (AEDT): 4+ hours of buffer and lounge. Any QF flight landing before 3pm Sydney time works.'),
      dict(id='opt-qf-mcy', rank=2, label='Qantas QF903 Sunshine Coast → Sydney', route='MCY → SYD T3', date='2027-02-08', dep='12:15', arr='15:05', duration='1h40', cashAud=160, priceNote='from ~A$130', points=9200, pointsTaxAud=58, status='idea', notes='1 h from Gympie, parking ~A$90 for 8 days, no tolls. But if QF903 is cancelled the next Qantas flight lands after QF481 has gone, and the homeward flight lands at Brisbane, so you would need a A$55-85 shuttle back to the car. Times shown in Sydney time (AEDT).'),
      dict(id='opt-jq-mcy', rank=3, label='Jetstar JQ787 Sunshine Coast → Sydney', route='MCY → SYD T2', date='2027-02-08', dep='11:30', arr='14:15', duration='1h45', cashAud=90, priceNote='from ~A$67 + bag', status='idea', notes='Cheapest fare, but arrives T2: collect bags, walk 7 min to T3, re-check, re-screen. No through-checking to Narita.'),
      dict(id='opt-qf905', rank=4, label='Qantas QF905 Sunshine Coast → Sydney, 7am (safest from MCY)', route='MCY → SYD T3', date='2027-02-08', dep='07:00', arr='09:50', duration='1h40', cashAud=150, points=9200, pointsTaxAud=58, status='idea', notes='Lowest risk if you insist on MCY: a whole day of fallback options. Long day in Sydney though (8+ hours in the lounge).'),
    ]),
    dict(id='leg-home', name='Japan to home, Mon 15 Feb', chosenOptionId='opt-qf62-econ', notes='Big finding: the Brisbane flight (QF62) has no Premium Economy cabin at all, so “book economy and upgrade to PE” does not exist on it. The only Qantas Tokyo flight with PE is the 6:55am Haneda → Sydney. Realistic comfort upgrades: Economy Plus extra-legroom seats on the A330 (new from Sep 2026), or a Business Classic Reward if a seat appears. Points numbers marked “est.” are inferred from the Aug 2025 price rise; confirm on qantas.com when booking.', options=[
      dict(id='opt-qf62-econ', rank=1, label='QF62 Narita → Brisbane, Economy Classic Reward', route='NRT → BNE', date='2027-02-15', dep='21:45', arr='07:45', duration='~9h', cashAud=720, priceNote='cash from ~A$720', points=29000, pointsTaxAud=150, status='planned', notes='Recommended if a reward seat shows for 15 or 16 Feb. ~29,000 pts (est.) + ~A$120-170 taxes (Japan’s departure tax tripled to ¥3,000 from July 2026, so ex-Japan taxes are a little higher than older guides say). Add Economy Plus (extra legroom, ~19,500 pts or ~A$100-150 cash on similar routes) for comfort. Lands straight into Brisbane where the car is.'),
      dict(id='opt-qf62-bus', rank=2, label='QF62 Narita → Brisbane, Business Classic Reward', route='NRT → BNE', date='2027-02-15', dep='21:45', arr='07:45', duration='~9h', cashAud=3500, priceNote='cash ~A$3,000+', points=82100, pointsTaxAud=320, status='idea', notes='82,100 pts (confirmed post-Aug-2025 price) + ~A$250-350 taxes. You have the points. Availability at Bronze in peak February is the only question; set alerts.'),
      dict(id='opt-jq10', rank=3, label='Jetstar JQ10 Narita → Brisbane, economy', route='NRT → BNE', date='2027-02-15', dep='20:50', arr='06:45', duration='8h55', cashAud=409, priceNote='from ~A$409 + bag/meal', points=24000, pointsTaxAud=110, status='idea', notes='Cheapest points option (Jetstar table, ~24,000 pts est.; includes 20 kg bag). 787, no PE; you can bid for Jetstar Business with points + cash.'),
      dict(id='opt-jq24', rank=4, label='Jetstar JQ24 Osaka KIX → Brisbane (only if the trip is flipped to end in Osaka)', route='KIX → BNE', date='2027-02-15', dep='21:45', arr='07:25', duration='8h45', cashAud=420, priceNote='from ~A$400', points=24000, pointsTaxAud=110, status='idea', notes='Runs ~4x weekly; confirm Monday operates. Would let you do USJ on the last day and skip the Tokyo backtrack, at the cost of USJ on a Monday instead of Wednesday.'),
      dict(id='opt-qf26', rank=5, label='QF26 Haneda → Sydney, the only flight with Premium Economy', route='HND → SYD', date='2027-02-16', dep='06:55', arr='18:55', duration='~10h', cashAud=900, priceNote='economy cash est.', points=36200, pointsTaxAud=140, status='idea', notes='3-class A330 from Oct 2026. Economy ~36,200 pts est., PE ~74,000 pts est. Departs 6:55am (check-in from 4am, before trains run), so you would sleep at a Haneda hotel on the 15th and then still need SYD → Brisbane/Sunshine Coast. Only worth it if PE is the priority over everything else.'),
    ]),
  ],
  lounges=[
    dict(airport='Sydney T3 (Mon 8 Feb, ~2pm-6pm)', lounge='Qantas Domestic Business Lounge', access='yes', notes='Access comes from the Business cabin on your Classic Reward, not from status or passes. Entry opposite gates 4-5, up the escalator; Business Lounge is the left-hand door. Open until the last Qantas departure. Sydney’s First Lounge is in the international terminal (T1) and is not reachable from T3.'),
    dict(airport='Melbourne T2 (Mon 8 Feb, ~9pm-10:45pm)', lounge='Qantas International Business Lounge', access='yes', notes='Airside, level 1. Covered by the Business ticket. Melbourne Airport lists a 10:15pm Monday close, but Qantas says lounges stay open until the last departure and Monday QF49 is a new service from Dec 2026: re-check the hours in January and be at the gate by 10:45pm regardless.'),
    dict(airport='Melbourne T2, First Lounge (level 3), Mon 8 Feb ~9pm-10:45pm', lounge='Qantas International First Lounge', access='yes', notes='Confirmed: your two passes are Qantas Money Titanium First Lounge invitations, which are valid at the Sydney, Melbourne and Los Angeles First Lounges when you are flying on a QF or JQ flight number. Use ONE here: escalator near gates 9-10 up to level 3, show the invitation in the Qantas app. Sit-down dining (the Neil Perry menu), spa if you book on arrival, showers. The second pass cannot be used on this trip (Narita has no Qantas First Lounge and you leave Sydney from the domestic terminal), so keep it for a later international departure. Third-party listings put closing at 10:15-11:15pm; be at the gate by 10:45pm. Invitations are cardholder-only and expire, so check the expiry date in the app now.'),
    dict(airport='Brisbane domestic (Mon 8 Feb morning)', lounge='Qantas Club or Domestic Business Lounge', access='maybe', notes='Two routes in. (1) If your two passes turn out to be ordinary General/Domestic invitations, this is the one place on the trip they are useful: they open the Qantas Club here before an economy feeder. (2) Qantas/oneworld rule: Business passengers connecting the same day to a long-haul oneworld flight can use the Business Lounge before the domestic sector regardless of cabin; on a separate ticket that is at the agent’s discretion, so show the QF49 itinerary and ask nicely.'),
    dict(airport='Sunshine Coast (MCY)', lounge='No lounges at all', access='no', notes='Small terminal, four eateries, free wifi.'),
    dict(airport='Narita T2 (Mon 15 Feb)', lounge='Economy: none. Business reward: JAL Sakura Lounge', access='no', notes='If you end up on the Business reward home, Qantas uses the JAL Sakura Lounge at Narita. In economy there is no lounge access; the 4F food court is good.'),
  ],
)

points = dict(balance=170000, availableFrom='2026-10-15', notes='Prices confirmed post-5 Aug 2025: NRT→BNE Business 82,100; HND/NRT→SYD/MEL Business 98,400; short domestic (Zone 1) economy 9,200 + ~A$58. Economy Tokyo→Brisbane is estimated at ~29,000 (Zone 5) and Tokyo→Sydney/Melbourne ~36,200 (Zone 6); the exact cells were not visible from here, confirm on qantas.com. Bronze members are last in the upgrade queue and are typically only considered inside 24 h of departure, so treat any upgrade as a bonus, not a plan. Qantas’ Flight Reward Finder can be searched without logging in; AwardFares has a free Qantas search with alerts.')

stays = [
  # Osaka, 9-11 Feb (2 nights)
  dict(id='s-os1', name='Dormy Inn Premium Osaka Kitahama', town='Osaka', type='Business hotel with rooftop onsen bath', status='shortlist', pricePerNightAud=140, nights=2, priceNote='est. Feb; verify', checkIn='2027-02-09', checkOut='2027-02-11', distance='Kitahama: 20 min to Universal City by train; quiet business district by the river', url='https://www.booking.com/', notes='Dormy Inns are the solo traveller’s friend: free late-night ramen, big bath, small clean rooms. Kitahama is calm and central.'),
  dict(id='s-os2', name='Toyoko Inn Osaka Umeda Nakatsu No.1', town='Osaka', type='Budget business hotel', status='shortlist', pricePerNightAud=100, nights=2, priceNote='est. Feb; verify', checkIn='2027-02-09', checkOut='2027-02-11', distance='Nakatsu: 10 min walk to Nakazakicho, 20 min to USJ', url='https://www.toyoko-inn.com/eng/', notes='Cheapest reliable option. Free breakfast (onigiri, miso soup). Book direct; the chain often has Feb availability when others are full.'),
  dict(id='s-os3', name='Hotel Universal Port Vita', town='Osaka', type='Official partner hotel, 10 min walk to USJ', status='idea', pricePerNightAud=200, nights=2, priceNote='est. Feb; verify', checkIn='2027-02-09', checkOut='2027-02-11', distance='Universal City: walk to the park gates, early-entry perks on some plans', url='https://www.hoteluniversalportvita.com/', notes='Pay for convenience on USJ day only if the price is close. The Universal City area is a theme-park precinct, not a neighbourhood.'),
  # Nozawa Onsen, 11-15 Feb (4 nights)
  dict(id='s-nz1', name='Seisenso Inn (minshuku)', town='Nozawa Onsen', type='Family-run minshuku, private room, shared bath', status='shortlist', pricePerNightAud=90, nights=4, priceNote='from ~¥5,000 pp; single surcharge likely', checkIn='2027-02-11', checkOut='2027-02-15', distance='In the village, 5-10 min walk to Nagasaka gondola', url='https://nozawa-onsen.com/nozawa-accommodation/nozawa-onsen-ryokan-accommodation/', notes='Closest to the Banff-motel price point. Ask for a single tatami room with breakfast. The long-weekend dates fill first.'),
  dict(id='s-nz2', name='Minshuku Kojima', town='Nozawa Onsen', type='Minshuku, private room', status='shortlist', pricePerNightAud=95, nights=4, priceNote='from ~US$56; verify single rate', checkIn='2027-02-11', checkOut='2027-02-15', distance='Village centre', url='https://www.kayak.com/Nozawa-Onsen-Hotels-Minshuku-Kojima.2959745.ksp', notes='Simple, local-run, warm. Book by phone/email or via Booking.com.'),
  dict(id='s-nz3', name='Mid-range ryokan with dinner and breakfast (e.g. Kawamotoya, Nozawa View Hotel Shimataka)', town='Nozawa Onsen', type='Ryokan, half board', status='planned', pricePerNightAud=165, nights=4, priceNote='¥15,000-19,000 pp half board est.; verify', checkIn='2027-02-11', checkOut='2027-02-15', distance='5-8 min to the gondola', url='https://www.booking.com/', notes='Planned as the budget placeholder (about the Banff rate once dinner and breakfast are counted). A ryokan dinner is the local-cuisine experience you asked for, and it solves the solo-dinner question three nights out of four.'),
  dict(id='s-nz4', name='Lodge Nagano / Villa Nozawa (Aussie-run lodges)', town='Nozawa Onsen', type='Lodge, private room', status='idea', pricePerNightAud=150, nights=4, priceNote='est.; verify', checkIn='2027-02-11', checkOut='2027-02-15', distance='Village', url='https://www.nozawaholidays.com/', notes='Easy English, good beds, but you will be surrounded by Australians. Fallback if the Japanese-run places are full.'),
  # Alternative base
  dict(id='s-my1', name='Akakura Onsen ryokan (Myoko), if you swap bases', town='Myoko Kogen (alternative)', type='Onsen ryokan, per-person twin basis', status='idea', pricePerNightAud=80, nights=4, priceNote='¥8,400-9,200 pp twin basis; single rate unknown', checkIn='2027-02-11', checkOut='2027-02-15', distance='Ski-in walk to Akakura Onsen lifts', url='https://joetsu-myoko.com/joetsu-myoko-accommodation/akakura-onsen-accommodation-hotels/', notes='Quieter and cheaper than Nozawa, more Japanese, 13-16 m of snow, smaller mountain. See Decisions.'),
]

food = [
  dict(id='fd1', town='Nozawa Onsen', dish='Nozawana (pickled turnip greens)', where='Every meal; buy a bag from a village grandma’s shop to take home', why='The village’s signature food. Every family pickles its own; you will be offered it constantly.', priceBand='¥'),
  dict(id='fd2', town='Nozawa Onsen', dish='Oyaki', where='Street stalls near Oyu and at Nagano Station', why='Grilled-then-steamed buns filled with nozawana, pumpkin or bean paste. The Nagano snack.', priceBand='¥'),
  dict(id='fd3', town='Nozawa Onsen', dish='Shinshu soba at Sobadokoro Daimon', where='Main street, 100+ years in the Katagiri family', why='Hand-cut buckwheat noodles, cold zaru style with dipping sauce. Old shop, no fuss.', priceBand='¥¥'),
  dict(id='fd4', town='Nozawa Onsen', dish='Basashi (horse sashimi)', where='Any village izakaya', why='Nagano speciality, served with ginger and soy. Try it once.', priceBand='¥¥'),
  dict(id='fd5', town='Nozawa Onsen', dish='Onsen tamago from the Ogama', where='Ogama, top of the village', why='Eggs slow-cooked in the 90°C spring. Locals cook their vegetables there too; it is the village kitchen.', priceBand='¥'),
  dict(id='fd6', town='Nozawa Onsen', dish='Set dinner at Wakagiri', where='Main street', why='Home-style teishoku that locals actually eat. Not a ski-bar.', priceBand='¥¥'),
  dict(id='fd7', town='Osaka', dish='Okonomiyaki at a neighbourhood counter', where='Any counter with a hotplate in Fukushima or Tenma (avoid the Dotonbori queues)', why='Osaka’s home cooking. Sit at the teppan, order “buta-tama”, watch it made.', priceBand='¥'),
  dict(id='fd8', town='Osaka', dish='Doteyaki and kushikatsu in Tenma', where='Izakaya alleys under the tracks at Tenma station', why='Beef tendon simmered in miso, and the deep-fried skewers Osaka is known for, in the part of town where office workers drink. No double dipping.', priceBand='¥'),
  dict(id='fd9', town='Osaka', dish='Takoyaki from a street stand', where='A stand with a queue of locals, not the ones with English menus', why='Octopus balls, Osaka’s thing. Eat them standing up, straight away.', priceBand='¥'),
  dict(id='fd10', town='Osaka', dish='Kitsune udon', where='Usami-tei Matsubaya (the shop that claims to have invented it, near Minami-Semba)', why='Udon in dashi with sweet fried tofu, Osaka’s soul food. Old shop, cheap.', priceBand='¥'),
  dict(id='fd11', town='Osaka', dish='Yakiniku in Tsuruhashi (Korea Town)', where='Tsuruhashi station area', why='Osaka’s Korean neighbourhood; smoky yakiniku joints, nothing trendy about it. Good for a solo counter seat.', priceBand='¥¥'),
  dict(id='fd15', town='Osaka', dish='Kushikatsu at Yaekatsu (Shinsekai)', where='Shinsekai, a few doors from the famous Daruma', why='If you do go to Shinsekai, this is the locals’ pick over the tourist-famous Daruma. About ¥2,000 a head.', priceBand='¥'),
  dict(id='fd16', town='Osaka', dish='Fukushima izakaya under the tracks', where='Fukumaru-dori, one Loop Line stop from Osaka Station', why='A workers’ dining street lined with small izakaya and bars; a good alternative base for dinner if the hotel is around Fukushima.', priceBand='¥¥'),
  dict(id='fd12', town='On the way', dish='Ekiben (station bento)', where='Ekibenya Matsuri, Tokyo Station', why='Regional lunch boxes to eat on the Shinkansen. Pick one from Nagano or Niigata.', priceBand='¥'),
  dict(id='fd13', town='Nagano', dish='Shinshu miso ramen', where='Nagano Station area', why='Nagano is miso country. Warm you up after the Shinano train.', priceBand='¥'),
  dict(id='fd14', town='USJ', dish='Kinopio’s Cafe', where='Super Nintendo World', why='The one touristy meal that is worth it: themed, and you are already inside.', priceBand='¥¥'),
]

budget = [
  dict(id='bg1', category='Parking', label='Brisbane Airport AIRPARK, 8 days', amount=109, currency='AUD', status='estimate', notes='A$99/week + A$10/day. Book online; sometimes cheaper than drive-up. MCY would be ~A$90 but needs a A$55-85 shuttle back from Brisbane on the way home.'),
  dict(id='bg2', category='Transport', label='Fuel Gympie ↔ Brisbane Airport', amount=65, currency='AUD', status='estimate', notes='~167 km each way.'),
  dict(id='bg3', category='Insurance', label='Travel insurance with snow-sports cover, 9 days', amount=130, currency='AUD', status='estimate', notes='Must include skiing. Medicare does not cover Japan.'),
  dict(id='bg4', category='Connectivity', label='eSIM, 10 days data', amount=30, currency='AUD', status='estimate', notes='Ubigi or Airalo; install before you leave.'),
  dict(id='bg5', category='Food', label='Breakfasts, snacks, drinks, incidentals (¥3,000/day x 7)', amount=21000, currency='JPY', status='estimate'),
  dict(id='bg6', category='Other', label='Onsen towels, ski socks, souvenirs, contingency', amount=200, currency='AUD', status='estimate'),
  dict(id='bg7', category='Transport', label='Suica top-ups (local trains, buses, vending machines)', amount=5000, currency='JPY', status='estimate'),
  dict(id='bg8', category='Activities', label='USJ Express Pass 4 with Super Nintendo World entry (optional but recommended)', amount=12800, currency='JPY', status='estimate', notes='Nintendo-inclusive Express Pass 4 variants (e.g. “Mine Cart & Jaws”) were ~¥12,800 in 2026; Express Pass 7 ¥17,800-21,800. Names change every season: buy any Express Pass whose description includes “Super Nintendo World Area Entry” (ideally with Mario Kart and Mine-Cart Madness). Sells out on popular dates.'),
]

checklist = [
  dict(id='ck1', group='Before you go', text='Check what your two lounge passes actually are: Qantas app → Complimentary Lounge Invitations → type (Titanium / Platinum One / General / Domestic) and expiry', due='2026-09-30', notes='Only Titanium or Platinum One invitations open the Melbourne First Lounge. General/Domestic ones add nothing on this trip because the Business ticket already covers the Business lounges.'),
  dict(id='ck2', group='Points and bookings', text='Set free reward-seat alerts for QF62 NRT→BNE (and QF80, QF26) for 14-16 Feb 2027 on AwardFares; also try Qantas Flight Reward Finder (no login needed)', due='2026-09-20', notes='Peak February: seats come and go. Alerts do the watching for you.'),
  dict(id='ck3', group='Points and bookings', text='Book Nozawa Onsen accommodation for 11-15 Feb (long weekend; the village sells out)', due='2026-09-30', notes='Email the minshuku directly for a single room, or Booking.com. Ask about single-occupancy pricing and whether dinner is included.'),
  dict(id='ck4', group='Points and bookings', text='Book Osaka hotel for 9-11 Feb', due='2026-10-31', notes='Toyoko Inn / Dormy Inn open bookings ~3-6 months ahead. Free cancellation where possible.'),
  dict(id='ck5', group='Points and bookings', text='Points land: book the homeward Classic Reward (QF62 NRT→BNE, or the best available option) as soon as the balance shows', due='2026-10-16', notes='Log in, search Use Points, one-way NRT→BNE 15 Feb (try 16 Feb too). If Business shows at 82,100 and you want it, take it; otherwise Economy Classic and add Economy Plus.'),
  dict(id='ck6', group='Points and bookings', text='Book the Brisbane → Sydney feeder on a QF flight landing by 3pm AEDT (cash ~A$140 or 9,200 pts + A$58)', due='2026-10-20', notes='Same day, separate ticket. Consider the 9,200-point reward if you still have plenty left after the homeward booking.'),
  dict(id='ck7', group='Points and bookings', text='Book Brisbane AIRPARK online for 8-16 Feb', due='2026-11-30'),
  dict(id='ck8', group='Points and bookings', text='Buy USJ 1-Day Studio Pass + Express Pass 4 with Super Nintendo World entry for Wed 10 Feb (dates open 60 days ahead, so ~12 Dec 2026)', due='2026-12-12', notes='Official USJ site or Klook (official partner; Klook lets you move the date within 90 days in the same price tier). Buy the day it opens. Create the USJ app account now: since Jan 2026 the app is mandatory for timed-entry tickets.'),
  dict(id='ck9', group='Points and bookings', text='Travel insurance with the snow-sports add-on (and off-piste cover if you plan to ski Nozawa’s tree runs)', due='2026-11-30', notes='Standard Australian policies exclude skiing. About A$80 for a week before the add-on. Buy it when you book the first non-refundable thing so cancellation cover starts. Medicare does not cover Japan.'),
  dict(id='ck10', group='Points and bookings', text='Reserve Shinkansen and Shinano seats (smart-EX for Tokyo↔Osaka, JR East site for Hokuriku), opens 1 month before each travel date', due='2027-01-09', notes='9 Jan for the 9 Feb trains; 11 Jan for the 11 Feb trains; 15 Jan for the 15 Feb trains. Holiday Thursday trains fill.'),
  dict(id='ck11', group='Before you go', text='Register on Visit Japan Web (immigration + customs QR)', due='2027-01-20', notes='Australians get 90 days visa-free. Passport just needs to be valid for the stay, but check the expiry anyway.'),
  dict(id='ck12', group='Before you go', text='Install eSIM (Ubigi ~US$14 for 10 GB/7 days, or Airalo) and set up Welcome Suica Mobile (iPhone) or plan to buy a physical Welcome Suica at Narita (Android)', due='2027-01-31', notes='Suica works in Osaka (ICOCA area) and Nagano too. Google Wallet on non-Japanese Android phones generally cannot hold Suica; the physical Welcome Suica is cash top-up only and expires after 28 days, which is fine for this trip. Top up with Mastercard/Amex in Apple Wallet; some Visa cards fail.'),
  dict(id='ck13', group='Before you go', text='Re-check Melbourne T2 lounge hours for Monday nights (Business Lounge and, if your passes qualify, First Lounge)', due='2027-01-31'),
  dict(id='ck14', group='Before you go', text='Tell your bank you are travelling; get ¥30,000-50,000 cash (or plan to withdraw at 7-Eleven ATMs on arrival)', due='2027-02-01', notes='Ski villages and small restaurants are still cash-heavy.'),
  dict(id='ck15', group='Before you go', text='Book ski rental online (village shop) for Fri 12, Sat 13 and Mon 15 Feb with your boot size in cm; include ski wear if travelling light', due='2027-01-15', notes='Big boot sizes run out in peak weeks. Pick a shop that opens by 7:45 so Friday is not lost.'),
  dict(id='ck16', group='Packing', text='Ski: thermals, mid-layer, gloves, goggles, beanie, buff, ski socks x3 (rent jacket/pants/skis/boots/helmet)', due='2027-02-06'),
  dict(id='ck17', group='Packing', text='Onsen kit: small towel, plus a sense of humour about being naked with strangers', due='2027-02-06'),
  dict(id='ck18', group='Packing', text='Carry-on for the plane: passport, printed e-ticket, USJ tickets, chargers, Type-A power adapter (Japan is 100 V, US-style plugs), snacks', due='2027-02-07'),
  dict(id='ck19', group='In Japan', text='USJ: through the gate, open the app, claim Super Nintendo World timed entry within seconds (or use the Express Pass slot)', due='2027-02-10'),
  dict(id='ck20', group='In Japan', text='Keep the N’EX round-trip ticket somewhere safe for the trip back to Narita', due='2027-02-09'),
  dict(id='ck23', group='In Japan', text='Tax-free shopping is now a refund at the airport (from Nov 2026): pay the 10% tax at the till, keep receipts and passport scans, and allow time at Narita to claim it back on Nintendo World or Osaka souvenirs', due='2027-02-15'),
  dict(id='ck24', group='Before you go', text='Open the Qantas app → Complimentary Lounge Invitations and confirm the Titanium First Lounge invitations show with an expiry after 8 Feb 2027', due='2026-09-30', notes='They renew each card anniversary. If the current pair expires before February, the next pair will be issued on the anniversary; check which.'),
  dict(id='ck25', group='Points and bookings', text='Ask the Nozawa lodging (when booking) whether they accept a courier parcel before arrival, and get their address in Japanese for the takkyubin slip', due='2026-10-31'),
  dict(id='ck26', group='Points and bookings', text='Reserve the Shinano seats Nagoya → Kiso-Fukushima and Shiojiri → Nagano for Thu 11 Feb, plus the local train times to and from Narai', due='2027-01-11', notes='Holiday Thursday: reserved seats go. The local Chuo line runs roughly hourly, so match the connections when you book.'),
  dict(id='ck27', group='Before you go', text='Buy simple strap-on crampons (or plan to buy at Workman/Don Quijote in Osaka) for the Togakushi snow walk', due='2027-02-01'),
  dict(id='ck28', group='In Japan', text='Saturday night: check Sunday’s weather. Powder dump = ski; anything else = Togakushi. Check the Alpico winter bus 70 timetable for the first bus and the last bus back', due='2027-02-13'),
  dict(id='ck21', group='Coming home', text='Return rental gear; settle the lodging bill in cash if they do not take cards', due='2027-02-15'),
  dict(id='ck22', group='Coming home', text='QF62 check-in closes 8:45pm at Narita T2', due='2027-02-15'),
]

places = [
  dict(id='p1', name='Gympie (home)', kind='town', town='Queensland', lat=-26.19, lng=152.665),
  dict(id='p2', name='Brisbane Airport (BNE)', kind='airport', town='Brisbane', lat=-27.3842, lng=153.1175, notes='AIRPARK long stay, free shuttle.'),
  dict(id='p3', name='Sunshine Coast Airport (MCY)', kind='airport', town='Marcoola', lat=-26.6033, lng=153.0910, notes='Alternative departure airport. No lounge.'),
  dict(id='p4', name='Sydney Airport T3', kind='airport', town='Sydney', lat=-33.9399, lng=151.1753, notes='Qantas domestic. Business Lounge opposite gates 4-5.'),
  dict(id='p5', name='Melbourne Airport T2', kind='airport', town='Melbourne', lat=-37.6690, lng=144.8410, notes='International. Business Lounge level 1, First Lounge level 3.'),
  dict(id='p6', name='Narita Airport T2', kind='airport', town='Narita', lat=35.7720, lng=140.3929, notes='Arrive 9 Feb, depart 15 Feb.'),
  dict(id='p7', name='Tokyo Station', kind='station', town='Tokyo', lat=35.6812, lng=139.7671, notes='N’EX arrives here; Shinkansen to Osaka and Nagano.'),
  dict(id='p8', name='Shin-Osaka Station', kind='station', town='Osaka', lat=34.7335, lng=135.5002),
  dict(id='p9', name='Universal Studios Japan', kind='park', town='Osaka', lat=34.6654, lng=135.4323, notes='Super Nintendo World. Universal City station is 5 min walk.'),
  dict(id='p10', name='Tenma / Tenjinbashisuji', kind='food', town='Osaka', lat=34.7043, lng=135.5133, notes='Izakaya alleys and the long arcade.'),
  dict(id='p11', name='Nakazakicho', kind='town', town='Osaka', lat=34.7090, lng=135.5060, notes='Old lanes, small cafes, 10 min from Umeda.'),
  dict(id='p19', name='Fukushima (Osaka) dining street', kind='food', town='Osaka', lat=34.6960, lng=135.4870, notes='Fukumaru-dori under the Loop Line tracks.'),
  dict(id='p20', name='Tsuruhashi (Korea Town) yakiniku', kind='food', town='Osaka', lat=34.6650, lng=135.5320, notes='Tsuruichi (1949), Aji Yoshi, Horumon Sora.'),
  dict(id='p21', name='Narai-juku', kind='town', town='Kiso valley', lat=35.9670, lng=137.8100, notes='Edo-period post town on the Nakasendo. Bag-minding at the station ¥300.'),
  dict(id='p22', name='Kiso-Fukushima Station', kind='station', town='Kiso valley', lat=35.8420, lng=137.6930, notes='Shinano stops here; change to the local train for Narai.'),
  dict(id='p23', name='Togakushi Okusha (inner shrine) entrance', kind='other', town='Togakushi', lat=36.7620, lng=138.0870, notes='Start of the cedar avenue; winter bus stop.'),
  dict(id='p24', name='Zenko-ji temple', kind='other', town='Nagano', lat=36.6617, lng=138.1876, notes='Get off bus 70 at Zenkoji Daimon.'),
  dict(id='p12', name='Nagoya Station', kind='station', town='Nagoya', lat=35.1709, lng=136.8815, notes='Change from Nozomi to the Shinano limited express.'),
  dict(id='p13', name='Nagano Station', kind='station', town='Nagano', lat=36.6431, lng=138.1887, notes='Soba and oyaki in the station.'),
  dict(id='p14', name='Iiyama Station', kind='station', town='Iiyama', lat=36.8500, lng=138.3600, notes='Nozawa Onsen Liner bus leaves from here.'),
  dict(id='p15', name='Nozawa Onsen village', kind='town', town='Nozawa Onsen', lat=36.9230, lng=138.4420, notes='13 free bathhouses; Oyu in the centre.'),
  dict(id='p16', name='Nozawa Onsen Snow Resort (Nagasaka gondola)', kind='resort', town='Nozawa Onsen', lat=36.9190, lng=138.4470, notes='297 ha, 1,085 m vertical.'),
  dict(id='p17', name='Akakura Onsen (Myoko), alternative base', kind='resort', town='Myoko', lat=36.8830, lng=138.1600, notes='Runner-up option: quieter, cheaper, deeper snow, smaller mountain.'),
  dict(id='p18', name='Hakuba Happo-One, alternative', kind='resort', town='Hakuba', lat=36.6980, lng=137.8320, notes='Biggest terrain, most international.'),
]

questions = [
  dict(id='q1', question='Ski base: Nozawa Onsen, Myoko (Akakura Onsen) or Hakuba?', why='You said “south island”, which does not exist for skiing (Japan’s ski areas are on Hokkaido in the north and in the Nagano/Niigata mountains on the main island). Given Narita arrival + Osaka + a week, Nagano/Niigata is the only sensible region. Nozawa is the closest thing to Banff: a real village, walkable, hot springs, mountain rising straight off it, local food. It is also the most Australian of the villages and the busiest over the 11-14 Feb long weekend.', options=['Nozawa Onsen (planned): Banff-like village, big mountain, local food, busiest and priciest of the three that weekend', 'Myoko / Akakura Onsen: quieter, cheaper, more Japanese, 13-16 m of snow, smaller mountain, fiddlier buses', 'Hakuba: biggest terrain and most Banff-like scale, but a sprawl of villages linked by buses and very international'], recommendation='Nozawa Onsen. If you decide “not hyped” matters more than terrain, switch to Myoko: the plan only changes at the Nagano end (Shinkansen to Joetsu-Myoko instead of Iiyama).', answer='', resolved=False),
  dict(id='q2', question='Trip shape: Universal Studios first (Wednesday) or ski first and fly home from Osaka?', why='Wed 10 Feb is the only calm weekday for USJ in the window (Thu 11 is a public holiday and the weekend follows, plus the tail of Lunar New Year travel). That forces the skiing onto the long weekend. The alternative is ski Wed-Fri (quieter slopes on Wed), then USJ on Mon 15 and fly Jetstar Osaka → Brisbane at 9:45pm that night, no Tokyo backtrack.', options=['USJ Wed 10, ski Fri-Mon, fly QF62 Narita → Brisbane Mon 15 (planned)', 'Ski Wed-Fri, Osaka Sat-Mon, USJ Mon 15, Jetstar JQ24 Osaka → Brisbane Mon 15 night'], recommendation='Keep USJ on the Wednesday. Super Nintendo World on a crowded day is the thing most likely to spoil the trip, and Nozawa is big enough to absorb a weekend if you start at 8:30. Monday morning skiing is the bonus.', answer='', resolved=False),
  dict(id='q3', question='Park at Brisbane or Sunshine Coast?', why='Sunshine Coast is closer (1 h vs 1h45) and parking is ~A$20 cheaper, but it has only 3 Qantas flights a day (a cancellation of the midday one leaves nothing that beats your 6:30pm departure) and the flight home lands at Brisbane, so you would pay A$55-85 and 2 hours for a shuttle back to the car. Brisbane wins once the return is counted.', options=['Brisbane: AIRPARK ~A$109, QF feeder with ~18 daily fallbacks, land straight at the car on 16 Feb (planned)', 'Sunshine Coast: ~A$90 parking, QF903 at 12:15 or the 7am QF905, then shuttle from Brisbane on the way home'], recommendation='Brisbane. It is cheaper overall and it protects the Business reward ticket, which is the most valuable thing in this trip.', answer='', resolved=False),
  dict(id='q4', question='How to use the points for the flight home?', why='The upgrade-to-Premium-Economy idea does not work on the Brisbane flight: QF62 is a two-class A330 with no PE cabin. The only Qantas Tokyo flight with PE leaves Haneda at 6:55am for Sydney. You have 170k points; Business on QF62 is 82,100 (confirmed price), Economy about 29,000 (estimate).', options=['Economy Classic Reward on QF62 (~29k est.) + Economy Plus extra legroom (~19.5k pts or ~A$100-150) (planned)', 'Business Classic Reward on QF62 (82,100 + ~A$300 taxes) if a seat shows', 'Jetstar JQ10 Narita → Brisbane on points (~24k est.) or cash (~A$409), bid for Jetstar Business', 'Cash economy on QF62 (~A$720) in an upgradeable fare class and hope: PE does not exist on this flight, so no'], recommendation='Search both Economy and Business Classic on 15 and 16 Feb the day the points land. Take Business if it is there; otherwise Economy Classic plus Economy Plus. Keep alerts running until departure because seats get released in batches.', answer='', resolved=False),
  dict(id='q5', question='What are the two “first class lounge passes”, exactly?', why='Answered: they are Qantas Money Titanium card First Lounge invitations. Valid at the Sydney, Melbourne and LA First Lounges on a QF/JQ flight, cardholder only.', options=['Use one at Melbourne T2 First Lounge on 8 Feb', 'Second one is unusable on this trip; keep it'], recommendation='Use one in Melbourne on 8 Feb; check the expiry in the Qantas app.', answer='Titanium credit card passes. One will be used in Melbourne; the other saved.', resolved=True),
  dict(id='q6', question='Rent ski gear or bring your own?', why='Rental in Nozawa is ~¥4,450-5,500 a day for skis, boots and poles, so 4 days is about A$165-200. Bringing skis means a 32 kg-allowance bag on the outbound (fine in Business) but hauling it through Tokyo Station, Osaka and two bus changes, plus the Shinkansen oversized-baggage rule.', options=['Rent everything in the village, bring only boots if you love yours (planned)', 'Bring skis and boots'], recommendation='Rent. This trip has too many trains for a ski bag. Bring your own boots only if fit is a problem for you.', answer='', resolved=False),
  dict(id='q7', question='Fly home Monday 15 or Tuesday 16 Feb?', why='Monday keeps to “about a week” and lands you home Tuesday morning. Tuesday gives a full quiet Monday on the slopes (the emptiest day) and a relaxed trip to Narita, one more night of lodging (~A$150) and a day of leave.', options=['Mon 15 Feb, QF62 21:45 (planned)', 'Tue 16 Feb, same flight, with a Monday ski day and a Narita airport hotel'], recommendation='Monday, unless the Business reward only shows on Tuesday, in which case take Tuesday and enjoy the extra ski day.', answer='', resolved=False),
  dict(id='q8', question='Keep this repo public?', why='The repo is public right now. That is why the app never writes booking references, ticket numbers or passport details to the repo (they live in the Private vault on your device). It is still safer to make the repo private since GitHub Pages works on private repos with a paid plan, or you can simply keep the rule: nothing sensitive in the plan text.', options=['Keep public, keep sensitive details in the vault only (current)', 'Make the repo private (Settings → General → Danger zone). Pages on private repos needs GitHub Pro.'], recommendation='Keep public for now and use the vault; revisit if you want to store confirmation emails in the repo.', answer='', resolved=False),
  dict(id='q10', question='Give up Sunday’s skiing for Togakushi and Zenko-ji, or fly home Tuesday to keep three full ski days?', why='You asked for a rural day and said a ski day could go. Narai-juku is now built into Thursday’s travel day at no cost. Sunday is the worst ski day (long-weekend crowds), so it is the cheapest one to trade for Togakushi’s cedar avenue and Zenko-ji. That leaves Friday, Saturday and Monday morning on skis. Flying home Tuesday 16 instead would add a full quiet Monday on the slopes for about A$150 of lodging plus a day of leave.', options=['Sunday rural day, Monday morning ski, fly Mon 15 (planned)', 'Sunday rural day and fly Tue 16 so Monday is a full ski day', 'Keep skiing Sunday; rural Japan is just the Narai stop on Thursday'], recommendation='As planned, with the powder-day escape hatch: if Sunday dawns dumping, ski and skip Togakushi.', answer='', resolved=False),
  dict(id='q11', question='Which rural stop, if you want a different one?', why='Alternatives to Togakushi from Nozawa: Obuse (30 min from Nagano by Nagaden train, chestnut sweets, the Hokusai museum, sake brewery, old streets; easy and flat) or a dawn visit to Zenko-ji’s o-asaji morning service. Shirakawa-go’s farmhouses are the postcard but are 4+ hours each way from Nozawa and heavily touristed; not worth it on this trip. Matsumoto castle is a city.', options=['Togakushi + Zenko-ji (planned): mountain shrine, cedars, soba, snow walk', 'Obuse + Zenko-ji: gentler, indoor-heavy, good if the weather is foul', 'Nothing beyond Narai'], recommendation='Togakushi, with Obuse as the bad-weather substitute.', answer='', resolved=False),
  dict(id='q9', question='Rough budget ceiling?', why='The plan currently totals roughly A$2,700-3,300 in cash on top of points, depending on Osaka hotel and the Express Pass. Knowing your ceiling decides whether to trade the ryokan half-board for a minshuku, and whether the Express Pass stays in.', options=['Under A$2,500: minshuku, skip Express Pass, Jetstar home', 'A$2,500-3,500: as planned', 'Over A$3,500: ryokan with dinner every night, Business home if available'], recommendation='As planned. The Express Pass is the one “splurge” that buys back a whole day.', answer='', resolved=False),
]

FOOD_GUIDE = [
  dict(title='How to tell a place is happy to have you', body='Green lights: a menu or prices visible outside, a ticket machine (ramen, soba, gyudon), plastic food models, a photo or English menu, a listing on Tabelog, staff who call “irasshaimase” when the door opens, and any yakiniku, okonomiyaki, udon or soba shop. Nozawa, Tenma, Fukushima, Tsuruhashi and Narai are all used to visitors; you are not intruding.'),
  dict(title='When to bow out', body='A sign reading 一見さんお断り (ichigen-san okotowari, “first-timers not accepted”) or 会員制 (members only); a tiny “snack” bar with a hostess and no price list; a six-seat counter where every seat is a regular and the master does not look up. Being turned away is not an insult: a small bow, “sumimasen”, and try the next door. That system is mostly Kyoto tea-house culture anyway; Osaka standing bars welcome anyone who orders a drink.'),
  dict(title='Manners that matter more than language', body='Order a drink first, then food. The small dish that arrives unasked (otoshi) is a cover charge, not a mistake. One drink and a couple of plates, then move on when it is crowded; angle your body to make room at a standing bar. Cash out, no tipping ever. No photos of other customers or the counter without a nod from the master. “Oishii” and “gochisosama deshita” (thanks for the meal) on the way out go a long way.'),
  dict(title='Onsen and ryokan', body='Shoes off at the genkan, slippers off on tatami. Ryokan dinner is at a set time; be there. In the bathhouses: wash sitting down before you get in, no towel in the water, no swimwear, quiet, no phones. Tattoos: Nozawa’s village bathhouses are relaxed but cover-up stickers are cheap insurance if you have visible ink.'),
]

trip = dict(
  meta=dict(title='Japan 2027', start='2027-02-08', end='2027-02-16', homeCurrency='AUD', jpyPerAud=RATE, updatedAt=UPDATED, version=1,
            about='Solo ski trip. Confirmed: Business Classic Reward SYD→MEL→NRT on 8 Feb. Everything else is planned from research done 13 Sep 2026; prices marked est. need checking when booking.'),
  days=days,
  flights=dict(
    confirmed=[{('from' if k == 'from_' else k): v for k, v in f.items()} for f in flights['confirmed']],
    legs=flights['legs'],
    lounges=flights['lounges'],
  ),
  foodGuide=FOOD_GUIDE, points=points, stays=stays, food=food, budget=budget, checklist=checklist, places=places, questions=questions,
)
with open('data/trip.json', 'w') as f:
    json.dump(trip, f, ensure_ascii=False, indent=2); f.write('\n')
print('wrote data/trip.json', sum(len(d['items']) for d in days), 'items,', len(stays), 'stays,', len(food), 'food,', len(checklist), 'todos,', len(questions), 'questions')
